/* Generato da build.py del secondo cervello (--sito). Non modificare a mano:
   il testo si cambia in testo-articolo.md, lo stile in stile.css. */
export default `<div class="hero">
  <nav class="briciole" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li><a href="/use-cases">Case studies</a></li><li aria-current="page">ADifesa</li></ol></nav>
  <div class="hero-griglia">
    <div class="hero-testo">
      <h1>Five months in the comments on Facebook and Instagram</h1>
      <p class="sub">2,329 conversations handled and 524 records complete with name, phone and email. Three in ten of those become clients.</p>
      <div class="cliente"><span class="tile"><img src="/assets/images/client-logos/adifesa.png" alt="ADifesa" width="67" height="48"></span><div><b>Associazione ADifesa</b><span class="dove">Consumer-protection association · Lissone, Italy</span></div></div>
    </div>
    <figure class="thread"><p class="et">From the comment to the private message</p><img class="scatto-img" src="/assets/images/casi/adifesa-2-messenger-apertura.png" alt="Screenshot of ADifesa&#x27;s message inbox: Meta warns that this is a reply to a comment on a Page post, the assistant asks for phone, email and call-back times, and the person leaves them at 11:07pm on a Saturday." width="744" height="318" loading="eager" decoding="async"><figcaption>A real screenshot of ADifesa’s inbox. At the top it is Meta itself stating that the conversation started from a comment under a post; the person replies at 11:07pm on a Saturday, leaving phone, email and call-back times. Name, photo and contact details are destroyed in the pixels, not covered by a layer.</figcaption></figure>
  </div>
  <aside class="breve"><span class="et">In short</span><p>From May 1 to September 16, 2026, an Automis automation handled 2,329 conversations across comments and private messages on Facebook and Instagram for ADifesa, a banking and financial consumer-protection association based in Lissone, Italy. They produced 1,033 qualified contacts and 524 records complete with name, phone and email. In 111 cases, fewer than one in twenty, the conversation was handed to a person. According to the association, 3 out of every 10 of those complete records become clients with at least one case opened.</p></aside>
</div>
<article class="corpo">
<section id="where-it-started"><h2>Where it started</h2>
<p>ADifesa is a consumer-protection association. It works for people who were charged costs they never owed on a salary-backed loan, a revolving credit card or a loan sold with an insurance policy, and it tries to get that money back. The assessment and the claim are free; the association is paid only out of what it recovers. Its office is in Lissone, near Milan, and it handles cases across Italy.</p>
<p>The Meta campaigns bring in completed forms, and that part already worked. The problem was everything around it: <strong>comments pile up under every ad</strong>, and requests land in the message inbox. These are people describing something private in public, namely how much they owe a bank.</p>
<p>Whoever writes there isn’t browsing. They have just read the ad and want one thing: <strong>to know whether their case qualifies</strong>. If nobody answers for a day, they take that question somewhere else.</p></section>
<section id="the-job-isn-t-replying-it-s-working-out-whether-the-case-qualifies"><h2>The job isn’t replying, it’s working out whether the case qualifies</h2>
<p>This is the part people underestimate. Anyone can reply “send us a private message”. The value is knowing whether there is a case at all, and the association’s rules are tight.</p>
<p>There are <strong>ten active eligibility rules</strong>, across five product types, naming <strong>eleven banks and lenders</strong>. It isn’t a keyword list: each rule has its own window of years and its own conditions. Revolving cards count if they were opened between 2000 and 2017, except for two issuers where the window is wider. A Compass loan counts from 2011 to 2020, a Deutsche Bank or Findomestic one from 2017 to 2022, and only above a certain amount. Business credit lines only for companies trading for five years and above twenty thousand euros. Investment losses yes, cryptocurrency no.</p>
<p><strong>And before any of that, the automation has to work out what is being discussed.</strong> Nobody writes “salary-backed loan renewed in 2016” in a comment. They write that a fifth of their salary is being withheld, that they have a card that never ends, that they were sold insurance along with the loan. Those words have to lead to the right product, because the product decides whether a case exists.</p></section>
<section id="the-numbers"><h2>The numbers</h2>
<p class="nota"><em>Production data, May 1 to September 16, 2026.</em></p>
<figure class="imbuto"><div class="passo"><div class="gradino" style="width:100%;animation-delay:0ms"><span class="cifra">2,329</span><span class="et">conversations handled across comments and private messages</span></div></div><div class="passo"><div class="gradino" style="width:68%;animation-delay:90ms"><span class="cifra">1,033</span><span class="et">qualified contacts</span></div></div><div class="passo"><div class="gradino" style="width:55%;animation-delay:180ms"><span class="cifra">524</span><span class="et">complete records: name, phone, email, product</span></div></div><div class="passo esito"><div class="gradino" style="width:100%;animation-delay:270ms"><span class="cifra">3 in 10</span><span class="et">of those records becomes a client, with at least one case</span></div></div><figcaption>From the comment to the case. The last step is the association’s figure, not ours.</figcaption></figure>
<figure class="curva" style="--n:5" role="img" aria-label="Chart of conversations handled each month, from May to September 2026: May 523, Jun 470, Jul 760, Aug 355, Sep 221"><figcaption class="curva-testa"><span>Conversations per month</span><span class="tot">2,329 in total</span></figcaption><div class="barre"><div class="col" style="--h:68.8%;--i:0"><span class="v">523</span><span class="b"></span></div><div class="col" style="--h:61.8%;--i:1"><span class="v">470</span><span class="b"></span></div><div class="col dopo svolta" style="--h:100.0%;--i:2"><span class="svolta-et">July · Instagram</span><span class="v">760</span><span class="b"></span></div><div class="col dopo" style="--h:46.7%;--i:3"><span class="v">355</span><span class="b"></span></div><div class="col dopo" style="--h:29.1%;--i:4"><span class="v">221</span><span class="b"></span></div></div><div class="mesi" aria-hidden="true"><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div><div class="anni" aria-hidden="true"><span>2026</span></div><p class="nota">From July, Instagram direct messages come in too. Volume follows the association’s campaigns, which were scaled back from August. September through the 16th.</p></figure>
<div class="tab"><table><tbody><tr><td>Conversations handled</td><td><strong>2,329</strong></td></tr><tr><td>Different people</td><td><strong>1,794</strong></td></tr><tr><td>Qualified contacts</td><td><strong>1,033</strong></td></tr><tr><td>Complete records, with name, phone and email</td><td><strong>524</strong></td></tr><tr><td>Handed to a person</td><td><strong>111</strong> (4.8%)</td></tr><tr><td>Private messages received</td><td><strong>2,951</strong></td></tr><tr><td>Private replies written by the automation</td><td><strong>1,676</strong></td></tr><tr><td>Public replies under comments</td><td><strong>1,262</strong></td></tr></tbody></table></div>
<p>Of those 2,329 conversations, 1,065 started as a comment under an ad, 232 as a comment under a post and 1,032 as a direct message.</p>
<p>But the first number we look at isn’t the total, it’s the <strong>524 complete records</strong>: name, phone, email and product, which is what an adviser needs to pick up the phone already knowing what the call is about.</p></section>
<section id="half-of-these-people-write-when-the-office-is-closed"><h2>Half of these people write when the office is closed</h2>
<p>Of the 2,951 private messages received, <strong>1,377 arrived outside working hours</strong>, that is 46.7%: 850 on weekdays before nine or after six, 527 at the weekend, 267 between ten at night and seven in the morning.</p>
<p>It’s the easiest number in the project to underrate. It doesn’t say the automation is fast, it says <strong>almost half of these requests arrive when there is nobody there to read them</strong>. They come on the evenings and Sundays when someone sits down with their statements, and that is exactly when they decide to write.</p></section>
<section id="a-phone-number-under-a-post-is-a-problem-not-a-lead"><h2>A phone number under a post is a problem, not a lead</h2>
<p>It happens constantly: someone types their phone number into the comment, in the open, under the ad. They want a call back. Meanwhile anyone passing by can read that number.</p>
<p>The automation treats it as an incident to close, not a lead to bank: <strong>when a comment contains a phone number or a sensitive detail, it hides the comment</strong> and moves the conversation into private messages. This applies under ads and under organic posts, on Facebook and on Instagram.</p>
<p>Public comments also get a deliberate three-minute wait before the reply goes up. That isn’t slowness: a reply that appears the same second someone finishes typing tells everyone there is a machine underneath.</p></section>
<section id="when-it-hands-over-to-a-person-and-why"><h2>When it hands over to a person, and why</h2>
<p><strong>111 conversations out of 2,329</strong>, fewer than one in twenty, were handed to someone on the team. The automation closed everything else on its own.</p>
<p>Control stays with the client, and this is the piece a demo never shows: from the control panel the association <strong>switches the automation off on a single conversation</strong> and carries on by hand, without touching the others. From that moment the chat is theirs and the bot stays out of it.</p>
<p>Then there is a rule that sounds trivial and isn’t: <strong>never dance around the fee.</strong> The association does get paid, as a percentage of what it recovers. In the comments, “what does this cost me” comes up every day, often with an edge to it. The reply says the assessment and the claim are free and that you pay only if the refund arrives, and it doesn’t try to move the question into private. With an audience that has heard too many promises already, an evasive answer is worth less than nothing.</p>
<figure class="scatto"><img class="scatto-img" src="/assets/images/casi/adifesa-1-facebook-commenti.png" alt="A comment thread under an ADifesa post: asked &quot;is this paid?&quot;, the Page answers in public that the assessment and the claim are free and that a fee is due only if the refund arrives." width="779" height="664" loading="lazy" decoding="async"><figcaption>Real comments under a post from September 18, 2026, in Italian. The question about cost comes in public, and the answer stays in public. Names and photos are destroyed in the pixels.</figcaption></figure></section>
<section id="instagram-came-later-and-it-shows"><h2>Instagram came later, and it shows</h2>
<p>The project started on Facebook. Instagram direct messages took an extra step: <strong>five permissions to be approved by Meta</strong>, each with a demonstration video.</p>
<p>The first submission, in May, was rejected. The five videos were re-shot on May 28 with a different method, showing the chain of identity between the Meta portal and the system, and that time it went through. Along the way came a detail worth the story on its own: <strong>Meta asked for a demonstration of a function that doesn’t exist in its own API</strong>, namely editing an Instagram comment. You can create, hide or delete one; you cannot edit it. The demonstration was rewritten around what the API actually does.</p>
<p>You can see the effect in the data, in qualified contacts coming from Instagram:</p>
<div class="tab motivi"><table><thead><tr><th scope="col">Month</th><th scope="col">Contacts</th></tr></thead><tbody><tr><td>May</td><td class="num"><span class="barra" style="--f:0.051" aria-hidden="true"></span>6</td></tr><tr><td>June</td><td class="num"><span class="barra" style="--f:0.248" aria-hidden="true"></span>29</td></tr><tr><td>July</td><td class="num"><span class="barra" style="--f:1.000" aria-hidden="true"></span>117</td></tr><tr><td>August</td><td class="num"><span class="barra" style="--f:0.188" aria-hidden="true"></span>22</td></tr><tr><td>September, to the 16th</td><td class="num"><span class="barra" style="--f:0.051" aria-hidden="true"></span>6</td></tr></tbody></table></div>
<figure class="scatto"><img class="scatto-img" src="/assets/images/casi/adifesa-3-instagram-dm.png" alt="An Instagram direct message conversation: the person asks for advice, the assistant asks for phone, email and call-back times, and gets them across three messages." width="953" height="722" loading="lazy" decoding="async"><figcaption>An Instagram direct message, August 24, 2026, in Italian. The purple bubbles are how Meta’s inbox tells Instagram apart from Messenger. Here the record is completed in three replies: phone and times first, then the email.</figcaption></figure></section>
<section id="the-post-that-cost-eighteen-dollars-a-day"><h2>The post that cost eighteen dollars a day</h2>
<p>In July one of the association’s posts went viral in the worst way: thousands of angry political comments, not one of them a case to take on. The automation read them one by one and correctly classified them as irrelevant, <strong>but to know that it had to call the model first</strong>. Around eighteen dollars a day burned answering nobody.</p>
<p>The fix wasn’t stricter filters, it was a counter. Every post keeps a tally of comments seen and how many turned out to be spam: past a threshold, <strong>that single post is muted</strong> and its comments never reach the model. In the window observed, 257 posts were tracked and 37 muted.</p>
<p>A muted post doesn’t go blind: words that point to a real product, like the name of a lender or “salary-backed loan”, still get through. We checked it against real comments rather than invented examples before it went live: no good case lost out of thirty-five tried, and all ten genuine leads recognised.</p></section>
<section id="what-we-got-wrong-and-fixed"><h2>What we got wrong, and fixed</h2>
<p>If we only told you what worked, it would be an ad.</p>
<ul><li><strong>“They withhold a fifth of my salary” was landing in spam.</strong> The filter discarded anyone talking about a fraction of their salary, to keep out generic venting. But a fifth is literally a fifth: the association’s main product was being mistaken for noise.</li><li><strong>People who commented again got the opening message twice.</strong> Someone already in a chat, coming back to comment under an ad, received a second “how can we help you?”. Now if the conversation is already open, the second message never goes out.</li><li><strong>Reels shared in private restarted the bot.</strong> Instagram sends a shared video as a message with no text, and the automation replied to every share. Now an attachment with no words gets no reply.</li><li><strong>On Instagram every contact was called “User c168f1”.</strong> The name was being read from a field that doesn’t exist on Instagram. Fixed, and the old names recovered: from 33 nameless contacts down to 4.</li></ul></section>
<section id="how-many-of-those-contacts-become-clients"><h2>How many of those contacts become clients</h2>
<p>Our database stops at the complete record. What happens next, once the adviser calls, only the association knows, so we asked them.</p>
<p>The answer: <strong>3 out of every 10 complete records become clients</strong>, with at least one case opened.</p>
<p>It is their number, out of their system rather than ours, and we report it as they gave it to us. It is worth reading for what it is: not 30% of everyone who comments, but 30% of the people who reached the end of the conversation and left a name, a phone number, an email and a product.</p></section>
<section id="what-these-numbers-don-t-say"><h2>What these numbers don’t say</h2>
<p>We don’t count the human work after a handover, because from that point the conversation continues inside Meta’s own tools and not in our system. And the outcome of the eligibility check isn’t recorded as such: the adviser makes that call, with the documents in hand.</p>
<p>How many refunds came through after that, and for how much, is not our figure and doesn’t belong here. A case study that promises revenue without holding the revenue figure is an ad in disguise.</p></section>
<section id="frequently-asked-questions"><h2>Frequently asked questions</h2>
<div class="faq"><details open><summary>How many conversations did the automation handle?</summary><p>From May 1 to September 16, 2026 it handled 2,329 conversations across comments and private messages on Facebook and Instagram, with 1,794 different people. They produced 1,033 qualified contacts and 524 records complete with name, phone and email.</p></details><details><summary>Does it answer public comments too, or only private messages?</summary><p>Both. Under a public comment it replies after a deliberate three-minute wait, and opens the private conversation in parallel. In the window observed it wrote 1,262 public replies and 1,676 private messages.</p></details><details><summary>What happens if someone posts their phone number in a comment?</summary><p>The comment is hidden and the conversation moves into private messages. A phone number sitting in the open under an ad is a risk to the person who wrote it, not a lead to collect.</p></details><details><summary>When does a person step in?</summary><p>Whenever the client decides: from the control panel the automation is switched off on that single conversation and the team carries on by hand. It happened on 111 conversations out of 2,329, fewer than one in twenty.</p></details><details><summary>How many of those contacts become clients?</summary><p>According to the association, 3 out of every 10 complete records become clients with at least one case opened. That is their figure, from their system: our database stops at the complete record, meaning name, phone, email and product.</p></details><details><summary>How long does it take to set up?</summary><p>It depends on how well defined the rules are. The long part isn’t the software, it’s writing down exactly when a case qualifies and when it doesn’t: here that meant ten rules with windows of years, minimum amounts and named lenders. For Instagram direct messages, factor in Meta’s approval of the permissions as well.</p></details></div></section>
<section id="the-close"><h2>The close</h2>
<p>If you run campaigns on Meta, there is already a queue of people under your ads asking you something. The question isn’t whether to answer automatically, it’s <strong>whether your rules are written well enough</strong> for someone else to answer in your place.</p>
<p>If you’d like to see how we work before we talk, here’s <a href="/ai-automations">how we build automations</a>.</p>
<div class="cta"><a class="btn" href="https://api.leadconnectorhq.com/widget/bookings/discover-automis" target="_blank" rel="noopener">Book a call</a><p>Thirty minutes, and we’ll tell you where we’d start.</p></div></section>
</article>`;
