/* Generato da build.py del secondo cervello (--sito). Non modificare a mano:
   il testo si cambia in testo-articolo.md, lo stile in stile.css. */
export default `<div class="hero">
  <nav class="briciole" aria-label="Breadcrumb"><ol><li><a href="/pt">Home</a></li><li><a href="/pt/use-cases">Casos de estudo</a></li><li aria-current="page">ADifesa</li></ol></nav>
  <div class="hero-griglia">
    <div class="hero-testo">
      <h1>Cinco meses nos comentários do Facebook e do Instagram</h1>
      <p class="sub">2.329 conversas tratadas e 524 fichas completas com nome, telefone e email. Dessas, 3 em cada 10 tornam-se clientes.</p>
      <div class="cliente"><span class="tile"><img src="/assets/images/client-logos/adifesa.png" alt="ADifesa" width="67" height="48"></span><div><b>Associazione ADifesa</b><span class="dove">Associação de defesa do consumidor · Lissone, Itália</span></div></div>
    </div>
    <figure class="thread"><p class="et">Do comentário à mensagem privada</p><img class="scatto-img" src="/assets/images/casi/adifesa-2-messenger-apertura.png" alt="Captura da caixa de mensagens da ADifesa: a Meta avisa que se está a responder a um comentário numa publicação da Página, o assistente pede telefone, email e horários, e a pessoa deixa-os às 23:07 de sábado." width="744" height="318" loading="eager" decoding="async"><figcaption>Captura real da caixa de entrada da ADifesa. No topo é a própria Meta a declarar que a conversa nasceu de um comentário sob uma publicação; a pessoa responde às 23:07 de um sábado e deixa telefone, email e horários de contacto. Nome, foto e contactos estão destruídos nos pixels, não tapados por uma camada.</figcaption></figure>
  </div>
  <aside class="breve"><span class="et">Em resumo</span><p>De 1 de maio a 16 de setembro de 2026, uma automação da Automis tratou 2.329 conversas entre comentários e mensagens privadas no Facebook e no Instagram para a ADifesa, associação italiana de defesa do consumidor bancário e financeiro, com sede em Lissone. Delas saíram 1.033 contactos qualificados e 524 fichas completas com nome, telefone e email. Em 111 casos, menos de um em vinte, a conversa passou para uma pessoa. Segundo a associação, 3 em cada 10 dessas fichas completas tornam-se clientes com pelo menos um processo aberto.</p></aside>
</div>
<article class="corpo">
<section id="o-ponto-de-partida"><h2>O ponto de partida</h2>
<p>A ADifesa é uma associação de defesa do consumidor. Acompanha quem pagou custos que não devia num crédito com garantia salarial, num cartão revolving ou num empréstimo vendido com uma apólice, e tenta reaver esse dinheiro. A peritagem e o recurso são gratuitos, e a associação só recebe sobre o que for recuperado. A sede fica em Lissone e os processos são acompanhados em toda a Itália.</p>
<p>As campanhas na Meta trazem formulários preenchidos, e essa parte já funcionava. O problema era tudo à volta: <strong>por baixo de cada anúncio acumulam-se comentários</strong>, e na caixa de mensagens chegam pedidos diretos. São pessoas que contam em público uma coisa privada, ou seja, quanto devem a um banco.</p>
<p>Quem escreve ali não está a passear. Acabou de ler o anúncio e quer saber uma coisa só: <strong>se o seu caso se enquadra</strong>. Se ninguém responder durante um dia, leva essa pergunta para outro lado.</p></section>
<section id="o-trabalho-nao-e-responder-e-perceber-se-o-processo-se-enquadra"><h2>O trabalho não é responder, é perceber se o processo se enquadra</h2>
<p>Esta é a parte que costuma ser subestimada. Responder «escreva-nos em privado» qualquer um sabe. O valor está em perceber se há caso, e as regras da associação são apertadas.</p>
<p>São <strong>dez regras de elegibilidade ativas</strong>, sobre cinco tipos de produto, e nomeiam <strong>onze bancos e financeiras</strong>. Não é uma lista de palavras: cada uma tem a sua janela de anos e as suas condições. Os cartões revolving contam se foram ativados entre 2000 e 2017, salvo dois emitentes em que a janela é mais larga. Um empréstimo Compass conta de 2011 a 2020, um do Deutsche Bank ou da Findomestic de 2017 a 2022, e acima de certo valor. O crédito em conta só para empresas, com cinco anos de atividade e acima de vinte mil euros. Perdas em investimentos sim, criptomoedas não.</p>
<p><strong>E antes disso a automação tem de perceber do que se fala.</strong> Nos comentários ninguém escreve «cessão de um quinto renovada em 2016». Escreve que lhe retêm um quinto do salário, que tem um cartão que nunca mais acaba, que lhe venderam um seguro junto com o empréstimo. É a partir dessas palavras que se tem de chegar ao produto certo, porque é o produto que decide se o caso existe.</p></section>
<section id="os-numeros"><h2>Os números</h2>
<p class="nota"><em>Dados de produção, de 1 de maio a 16 de setembro de 2026.</em></p>
<figure class="imbuto"><div class="passo"><div class="gradino" style="width:100%;animation-delay:0ms"><span class="cifra">2.329</span><span class="et">conversas tratadas entre comentários e mensagens privadas</span></div></div><div class="passo"><div class="gradino" style="width:68%;animation-delay:90ms"><span class="cifra">1.033</span><span class="et">contactos qualificados</span></div></div><div class="passo"><div class="gradino" style="width:55%;animation-delay:180ms"><span class="cifra">524</span><span class="et">fichas completas: nome, telefone, email, produto</span></div></div><div class="passo esito"><div class="gradino" style="width:100%;animation-delay:270ms"><span class="cifra">3 em 10</span><span class="et">dessas fichas torna-se cliente, com pelo menos um processo</span></div></div><figcaption>Do comentário ao processo. O último passo é um dado da associação, não nosso.</figcaption></figure>
<figure class="curva" style="--n:5" role="img" aria-label="Gráfico das conversas tratadas em cada mês, de maio a setembro de 2026: mai 523, jun 470, jul 760, ago 355, set 221"><figcaption class="curva-testa"><span>Conversas por mês</span><span class="tot">2.329 no total</span></figcaption><div class="barre"><div class="col" style="--h:68.8%;--i:0"><span class="v">523</span><span class="b"></span></div><div class="col" style="--h:61.8%;--i:1"><span class="v">470</span><span class="b"></span></div><div class="col dopo svolta" style="--h:100.0%;--i:2"><span class="svolta-et">Julho · Instagram</span><span class="v">760</span><span class="b"></span></div><div class="col dopo" style="--h:46.7%;--i:3"><span class="v">355</span><span class="b"></span></div><div class="col dopo" style="--h:29.1%;--i:4"><span class="v">221</span><span class="b"></span></div></div><div class="mesi" aria-hidden="true"><span>mai</span><span>jun</span><span>jul</span><span>ago</span><span>set</span></div><div class="anni" aria-hidden="true"><span>2026</span></div><p class="nota">A partir de julho chegam também as mensagens diretas do Instagram. O volume acompanha as campanhas da associação, reduzidas desde agosto. Setembro até ao dia 16.</p></figure>
<div class="tab"><table><tbody><tr><td>Conversas tratadas</td><td><strong>2.329</strong></td></tr><tr><td>Pessoas diferentes</td><td><strong>1.794</strong></td></tr><tr><td>Contactos qualificados</td><td><strong>1.033</strong></td></tr><tr><td>Fichas completas, com nome, telefone e email</td><td><strong>524</strong></td></tr><tr><td>Passadas a uma pessoa</td><td><strong>111</strong> (4,8%)</td></tr><tr><td>Mensagens privadas recebidas</td><td><strong>2.951</strong></td></tr><tr><td>Respostas privadas escritas pela automação</td><td><strong>1.676</strong></td></tr><tr><td>Respostas públicas sob comentários</td><td><strong>1.262</strong></td></tr></tbody></table></div>
<p>Dessas 2.329 conversas, 1.065 nasceram de um comentário sob um anúncio, 232 de um comentário sob uma publicação e 1.032 de uma mensagem direta.</p>
<p>Mas o primeiro número que olhamos não é o total, são as <strong>524 fichas completas</strong>: nome, telefone, email e produto, que é o que uma consultora precisa para pegar no telefone já a saber do que se trata.</p></section>
<section id="metade-destas-pessoas-escreve-com-o-escritorio-fechado"><h2>Metade destas pessoas escreve com o escritório fechado</h2>
<p>Das 2.951 mensagens privadas recebidas, <strong>1.377 chegaram fora do horário de trabalho</strong>, ou seja 46,7%: 850 em dias úteis antes das nove ou depois das seis, 527 ao fim de semana, 267 entre as dez da noite e as sete da manhã.</p>
<p>É o número mais fácil de subestimar em todo o projeto. Não diz que a automação é rápida, diz que <strong>quase metade dos pedidos chega quando não está lá ninguém para os ler</strong>. Chegam nas noites e nos domingos em que alguém se senta a olhar para as contas, e é exatamente aí que decide escrever.</p></section>
<section id="um-numero-de-telefone-debaixo-de-uma-publicacao-e-um-problema-nao-um-contacto"><h2>Um número de telefone debaixo de uma publicação é um problema, não um contacto</h2>
<p>Acontece muitas vezes: a pessoa escreve o seu número de telefone dentro do comentário, à vista de todos, por baixo do anúncio. Quer que lhe liguem. Entretanto aquele número é lido por quem ali passar.</p>
<p>A automação trata isso como um incidente a fechar, não como um contacto a arrecadar: <strong>quando um comentário tem um número de telefone ou um detalhe sensível, esconde o comentário</strong> e leva a conversa para as mensagens privadas. Vale sob os anúncios e sob as publicações orgânicas, no Facebook e no Instagram.</p>
<p>Nos comentários há também uma espera propositada de três minutos antes da resposta pública. Não é lentidão: uma resposta que aparece no mesmo segundo em que alguém acabou de escrever diz a toda a gente que por baixo está uma máquina.</p></section>
<section id="quando-passa-a-uma-pessoa-e-porque"><h2>Quando passa a uma pessoa, e porquê</h2>
<p><strong>111 conversas em 2.329</strong>, menos de uma em vinte, passaram para alguém da equipa. Todo o resto foi fechado pela automação sozinha.</p>
<p>O controlo fica do lado do cliente, e esta é a parte que numa demonstração nunca se vê: a partir do painel de controlo a associação <strong>desliga a automação numa conversa específica</strong> e continua à mão, sem tocar nas outras. A partir daí aquela conversa é dela e o bot não volta a escrever.</p>
<p>Há ainda uma regra que parece banal e não é: <strong>sobre a comissão não se dão voltas.</strong> A associação recebe, em percentagem sobre o recuperado. Nos comentários, a pergunta «quanto me custa» aparece todos os dias, muitas vezes em tom hostil. A resposta diz que a peritagem e o recurso são gratuitos e que só se paga se o reembolso chegar, e não tenta empurrar a pergunta para o privado. Num público que já ouviu promessas a mais, uma resposta evasiva vale menos do que nada.</p>
<figure class="scatto"><img class="scatto-img" src="/assets/images/casi/adifesa-1-facebook-commenti.png" alt="Fio de comentários sob uma publicação da ADifesa: à pergunta «é pago?», a Página responde em público que a peritagem e o recurso são gratuitos e que só se paga uma comissão se o reembolso chegar." width="779" height="664" loading="lazy" decoding="async"><figcaption>Comentários reais sob uma publicação de 18 de setembro de 2026, em italiano. A pergunta sobre o custo aparece em público, e a resposta fica em público. Nomes e fotos estão destruídos nos pixels.</figcaption></figure></section>
<section id="o-instagram-chegou-depois-e-nota-se"><h2>O Instagram chegou depois, e nota-se</h2>
<p>O projeto nasceu no Facebook. As mensagens diretas do Instagram exigiram um passo a mais: <strong>cinco permissões para aprovação da Meta</strong>, cada uma com um vídeo demonstrativo.</p>
<p>O primeiro envio, em maio, não passou. Os cinco vídeos foram repetidos a 28 de maio com outro método, mostrando a cadeia de identidade entre o portal da Meta e o sistema, e dessa vez correu bem. Pelo meio houve um detalhe que vale por si: <strong>a Meta pediu a demonstração de uma função que não existe na própria API</strong>, ou seja editar um comentário do Instagram. Pode criar-se, esconder-se ou apagar-se; editar não. A demonstração foi reescrita sobre aquilo que a API faz de facto.</p>
<p>O efeito vê-se nos dados, nos contactos qualificados vindos do Instagram:</p>
<div class="tab motivi"><table><thead><tr><th scope="col">Mês</th><th scope="col">Contactos</th></tr></thead><tbody><tr><td>Maio</td><td class="num"><span class="barra" style="--f:0.051" aria-hidden="true"></span>6</td></tr><tr><td>Junho</td><td class="num"><span class="barra" style="--f:0.248" aria-hidden="true"></span>29</td></tr><tr><td>Julho</td><td class="num"><span class="barra" style="--f:1.000" aria-hidden="true"></span>117</td></tr><tr><td>Agosto</td><td class="num"><span class="barra" style="--f:0.188" aria-hidden="true"></span>22</td></tr><tr><td>Setembro, até dia 16</td><td class="num"><span class="barra" style="--f:0.051" aria-hidden="true"></span>6</td></tr></tbody></table></div>
<figure class="scatto"><img class="scatto-img" src="/assets/images/casi/adifesa-3-instagram-dm.png" alt="Conversa numa mensagem direta do Instagram: a pessoa pede uma consulta, o assistente pede telefone, email e horários de contacto, e recebe-os em três mensagens." width="953" height="722" loading="lazy" decoding="async"><figcaption>Mensagem direta do Instagram, 24 de agosto de 2026, em italiano. As bolhas roxas são a forma como a caixa da Meta distingue o Instagram do Messenger. Aqui a ficha completa-se em três respostas: primeiro telefone e horários, depois o email.</figcaption></figure></section>
<section id="a-publicacao-que-custava-dezoito-dolares-por-dia"><h2>A publicação que custava dezoito dólares por dia</h2>
<p>Em julho uma publicação da associação tornou-se viral da pior maneira: milhares de comentários de desabafo político, nenhum deles um caso para acompanhar. A automação lia-os um a um e classificava-os corretamente como irrelevantes, <strong>mas para o saber tinha primeiro de chamar o modelo</strong>. Cerca de dezoito dólares por dia queimados a responder a ninguém.</p>
<p>A solução não foi apertar os filtros, foi um contador. Cada publicação guarda a conta dos comentários vistos e de quantos foram spam: passado um limite, <strong>aquela publicação fica em silêncio</strong> e os seus comentários deixam de chegar ao modelo. Na janela observada foram seguidas 257 publicações e silenciadas 37.</p>
<p>Uma publicação em silêncio não fica cega: as palavras que apontam para um produto real, como o nome de uma financeira, passam na mesma. A verificação foi feita sobre comentários reais e não sobre exemplos inventados: nenhum caso bom perdido em trinta e cinco testados, e os dez casos bons reconhecidos todos.</p></section>
<section id="o-que-corremos-mal-e-corrigimos"><h2>O que corremos mal, e corrigimos</h2>
<p>Se contássemos só o que correu bem, era publicidade.</p>
<ul><li><strong>«Retêm-me um quinto do salário» ia para spam.</strong> O filtro descartava quem falava de uma fração do salário, para travar os desabafos genéricos. Mas um quinto é literalmente um quinto: o principal produto da associação estava a ser confundido com ruído.</li><li><strong>Quem voltava a comentar recebia duas vezes a mensagem de abertura.</strong> Alguém já em conversa, que voltava a comentar sob um anúncio, recebia um segundo «como podemos ajudar?». Agora, se a conversa já está aberta, a segunda mensagem não sai.</li><li><strong>Os reels partilhados em privado faziam o bot arrancar de novo.</strong> O Instagram envia um vídeo partilhado como mensagem sem texto, e a automação respondia a cada partilha. Agora um anexo sem palavras não recebe resposta.</li><li><strong>No Instagram os contactos chamavam-se todos «Utilizador c168f1».</strong> O nome era lido de um campo que no Instagram não existe. Corrigido, e os nomes antigos recuperados: de 33 sem nome para 4.</li></ul></section>
<section id="quantos-desses-contactos-se-tornam-clientes"><h2>Quantos desses contactos se tornam clientes</h2>
<p>A nossa base de dados para na ficha completa. O que acontece depois, quando a consultora liga, só a associação sabe: perguntámos-lhe.</p>
<p>A resposta: <strong>3 em cada 10 fichas completas tornam-se clientes</strong>, com pelo menos um processo aberto.</p>
<p>É um número deles, que sai do sistema deles e não do nosso, e reproduzimo-lo tal como no-lo deram. Vale a pena lê-lo pelo que é: não 30% de quem comenta, mas 30% de quem chegou ao fim da conversa e deixou nome, telefone, email e produto.</p></section>
<section id="o-que-estes-numeros-nao-dizem"><h2>O que estes números não dizem</h2>
<p>Não contamos o trabalho das pessoas depois da passagem de mão, porque a partir daí a conversa continua dentro das ferramentas da Meta e não no nosso sistema. E o resultado da verificação de elegibilidade não fica registado como tal: quem decide é a consultora, com os documentos na mão.</p>
<p>Quantos reembolsos chegaram depois, e de que valores, não é um dado nosso e não entra aqui. Um caso de estudo que promete faturação sem ter o número da faturação é um anúncio disfarçado.</p></section>
<section id="perguntas-frequentes"><h2>Perguntas frequentes</h2>
<div class="faq"><details open><summary>Quantas conversas tratou a automação?</summary><p>De 1 de maio a 16 de setembro de 2026 tratou 2.329 conversas entre comentários e mensagens privadas no Facebook e no Instagram, com 1.794 pessoas diferentes. Delas saíram 1.033 contactos qualificados e 524 fichas completas com nome, telefone e email.</p></details><details><summary>Responde também aos comentários públicos ou só às mensagens privadas?</summary><p>A ambos. Sob o comentário público responde depois de uma espera propositada de três minutos, e em paralelo abre a conversa privada. Na janela observada escreveu 1.262 respostas públicas e 1.676 mensagens privadas.</p></details><details><summary>O que acontece se alguém escrever o número de telefone num comentário?</summary><p>O comentário é escondido e a conversa passa para as mensagens privadas. Um número de telefone à vista de todos sob um anúncio é um risco para quem o escreveu, não um contacto a recolher.</p></details><details><summary>Quando entra uma pessoa?</summary><p>Quando o cliente decide: a partir do painel de controlo a automação é desligada naquela conversa e a equipa continua à mão. Aconteceu em 111 conversas em 2.329, menos de uma em vinte.</p></details><details><summary>Quantos desses contactos se tornam clientes?</summary><p>Segundo a associação, 3 em cada 10 fichas completas tornam-se clientes com pelo menos um processo aberto. É um dado deles, do sistema deles: a nossa base de dados para na ficha completa, ou seja nome, telefone, email e produto.</p></details><details><summary>Quanto tempo demora a montar?</summary><p>Depende de quão definidas estão as regras. A parte demorada não é o software, é pôr por escrito quando um caso se enquadra e quando não: aqui foram dez regras com janelas de anos, valores mínimos e nomes de financeiras. Para as mensagens diretas do Instagram, há que contar também com a aprovação das permissões pela Meta.</p></details></div></section>
<section id="para-terminar"><h2>Para terminar</h2>
<p>Se faz campanhas na Meta, já existe por baixo dos seus anúncios uma fila de pessoas a perguntar-lhe alguma coisa. A questão não é se deve responder automaticamente, é <strong>se as suas regras estão escritas suficientemente bem</strong> para que outra pessoa possa responder no seu lugar.</p>
<p>Se quiser perceber como trabalhamos antes de falarmos, aqui fica <a href="/pt/ai-automations">como construímos as automações</a>.</p>
<div class="cta"><a class="btn" href="https://api.leadconnectorhq.com/widget/bookings/pt-automis" target="_blank" rel="noopener">Marcar uma chamada</a><p>Trinta minutos, e dizemos-lhe por onde começaríamos.</p></div></section>
</article>`;
