/* Generato da build.py del secondo cervello (--sito). Non modificare a mano:
   il testo si cambia in testo-articolo.md, lo stile in stile.css. */
export default `<div class="hero">
  <nav class="briciole" aria-label="Breadcrumb"><ol><li><a href="/it">Home</a></li><li><a href="/it/use-cases">Casi studio</a></li><li aria-current="page">ADifesa</li></ol></nav>
  <div class="hero-griglia">
    <div class="hero-testo">
      <h1>Cinque mesi nei commenti di Facebook e Instagram</h1>
      <p class="sub">2.329 conversazioni gestite e 524 schede complete di nome, telefono ed email. Di quelle, 8 su 10 diventano clienti.</p>
      <div class="cliente"><span class="tile"><img src="/assets/images/client-logos/adifesa.png" alt="ADifesa" width="67" height="48"></span><div><b>Associazione ADifesa</b><span class="dove">Associazione di tutela · Lissone (MB)</span></div></div>
    </div>
    <figure class="thread"><p class="et">Dal commento al messaggio privato</p><img class="scatto-img" src="/assets/images/casi/adifesa-2-messenger-apertura.png" alt="Schermata della casella messaggi di ADifesa: Meta avvisa che si sta rispondendo a un commento sotto un post della Pagina, l&#x27;assistente chiede telefono, email e orari, e la persona li lascia alle 23:07 di sabato." width="744" height="318" loading="eager" decoding="async"><figcaption>Schermata vera della casella di ADifesa. In cima è Meta a dichiarare che la conversazione nasce da un commento sotto un post; la persona risponde alle 23:07 di un sabato, e lascia telefono, email e orari di richiamo. Nome, foto e contatti sono distrutti nei pixel, non coperti da un livello.</figcaption></figure>
  </div>
  <aside class="breve"><span class="et">In breve</span><p>Dal 1° maggio al 16 settembre 2026 un’automazione di Automis ha gestito 2.329 conversazioni fra commenti e messaggi privati su Facebook e Instagram per ADifesa, associazione di tutela bancaria e finanziaria di Lissone. Ne sono usciti 1.033 contatti qualificati e 524 schede complete di nome, telefono ed email. In 111 casi, cioè meno di uno su venti, la conversazione è passata a una persona. Secondo l’associazione, 8 di quelle 10 schede complete diventano clienti con almeno una pratica aperta.</p></aside>
</div>
<article class="corpo">
<section id="il-punto-di-partenza"><h2>Il punto di partenza</h2>
<p>ADifesa è un’associazione di tutela bancaria e finanziaria. Segue chi ha pagato costi che non doveva su una cessione del quinto, una carta revolving, un prestito con polizza, e prova a farsi restituire quei soldi. Perizia e ricorso sono gratuiti, il compenso arriva solo sul recuperato. Sede a Lissone, in Brianza, e pratiche seguite in tutta Italia.</p>
<p>Le campagne su Meta portano moduli compilati, e quella parte funzionava già. Il problema era tutto intorno: <strong>sotto ogni inserzione si accumulano commenti</strong>, e nella casella dei messaggi arrivano richieste dirette. Sono persone che raccontano in pubblico una cosa privata, cioè quanto devono a una banca.</p>
<p>Chi scrive lì non è un curioso. È uno che ha appena letto l’annuncio e vuole sapere una cosa sola: <strong>se il suo caso rientra</strong>. Se non gli risponde nessuno per un giorno, quella domanda se la porta altrove.</p></section>
<section id="il-lavoro-non-e-rispondere-e-capire-se-la-pratica-rientra"><h2>Il lavoro non è rispondere, è capire se la pratica rientra</h2>
<p>Questa è la parte che di solito si sottovaluta. Rispondere «ci scriva in privato» lo sa fare chiunque. Il valore è capire se c’è un caso, e le regole dell’associazione sono strette.</p>
<p>Ci sono <strong>dieci regole di eleggibilità attive</strong>, su cinque tipi di prodotto, e nominano <strong>undici fra banche e finanziarie</strong>. Non è una lista di parole chiave: ognuna ha una finestra di anni e delle condizioni sue. Le carte revolving valgono se attivate fra il 2000 e il 2017, salvo due emittenti per cui la finestra è più larga. Un prestito Compass conta dal 2011 al 2020, uno Deutsche Bank o Findomestic dal 2017 al 2022, e sopra una certa cifra. Il fido bancario solo alle aziende, attive da cinque anni e sopra i ventimila euro. Le perdite su investimenti sì, le criptovalute no.</p>
<p><strong>E prima ancora l’automazione deve capire di cosa si sta parlando.</strong> Nei commenti nessuno scrive «cessione del quinto rinnovata nel 2016». Scrive che gli trattengono il quinto dello stipendio, che ha una carta che non finisce mai, che gli hanno venduto un’assicurazione insieme al prestito. È da quelle parole che si deve arrivare al prodotto giusto, perché è il prodotto a decidere se la pratica esiste.</p></section>
<section id="i-numeri"><h2>I numeri</h2>
<p class="nota"><em>Dati di produzione, dal 1° maggio al 16 settembre 2026.</em></p>
<figure class="imbuto"><div class="passo"><div class="gradino" style="width:100%;animation-delay:0ms"><span class="cifra">2.329</span><span class="et">conversazioni gestite fra commenti e messaggi privati</span></div></div><div class="passo"><div class="gradino" style="width:68%;animation-delay:90ms"><span class="cifra">1.033</span><span class="et">contatti qualificati</span></div></div><div class="passo"><div class="gradino" style="width:55%;animation-delay:180ms"><span class="cifra">524</span><span class="et">schede complete: nome, telefono, email, prodotto</span></div></div><div class="passo esito"><div class="gradino" style="width:100%;animation-delay:270ms"><span class="cifra">8 su 10</span><span class="et">di quelle schede diventa cliente, con almeno una pratica</span></div></div><figcaption>Dal commento alla pratica. L’ultimo passaggio è un dato dell’associazione, non nostro.</figcaption></figure>
<figure class="curva" style="--n:5" role="img" aria-label="Grafico delle conversazioni gestite ogni mese, da maggio a settembre 2026: mag 523, giu 470, lug 760, ago 355, set 221"><figcaption class="curva-testa"><span>Conversazioni al mese</span><span class="tot">2.329 in totale</span></figcaption><div class="barre"><div class="col" style="--h:68.8%;--i:0"><span class="v">523</span><span class="b"></span></div><div class="col" style="--h:61.8%;--i:1"><span class="v">470</span><span class="b"></span></div><div class="col dopo svolta" style="--h:100.0%;--i:2"><span class="svolta-et">Luglio · Instagram</span><span class="v">760</span><span class="b"></span></div><div class="col dopo" style="--h:46.7%;--i:3"><span class="v">355</span><span class="b"></span></div><div class="col dopo" style="--h:29.1%;--i:4"><span class="v">221</span><span class="b"></span></div></div><div class="mesi" aria-hidden="true"><span>mag</span><span>giu</span><span>lug</span><span>ago</span><span>set</span></div><div class="anni" aria-hidden="true"><span>2026</span></div><p class="nota">Da luglio arrivano anche i messaggi diretti di Instagram. Il volume segue le campagne dell’associazione, ridotte da agosto. Settembre fino al 16.</p></figure>
<div class="tab"><table><tbody><tr><td>Conversazioni gestite</td><td><strong>2.329</strong></td></tr><tr><td>Persone diverse</td><td><strong>1.794</strong></td></tr><tr><td>Contatti qualificati</td><td><strong>1.033</strong></td></tr><tr><td>Schede complete, con nome, telefono ed email</td><td><strong>524</strong></td></tr><tr><td>Passate a una persona</td><td><strong>111</strong> (4,8%)</td></tr><tr><td>Messaggi privati ricevuti</td><td><strong>2.951</strong></td></tr><tr><td>Risposte private scritte dall’automazione</td><td><strong>1.676</strong></td></tr><tr><td>Risposte pubbliche sotto i commenti</td><td><strong>1.262</strong></td></tr></tbody></table></div>
<p>Di quelle 2.329 conversazioni, 1.065 sono nate da un commento sotto un’inserzione, 232 da un commento sotto un post e 1.032 da un messaggio diretto.</p>
<p>Il numero che guardiamo per primo però non è il totale, sono le <strong>524 schede complete</strong>: nome, telefono, email e prodotto, cioè quello che serve a una consulente per alzare il telefono e sapere già di cosa si parla.</p></section>
<section id="meta-delle-persone-scrive-quando-l-ufficio-e-chiuso"><h2>Metà delle persone scrive quando l’ufficio è chiuso</h2>
<p>Dei 2.951 messaggi privati arrivati, <strong>1.377 sono fuori dall’orario di lavoro</strong>, cioè il 46,7%: 850 nei giorni feriali prima delle nove o dopo le sei, 527 nel fine settimana, 267 fra le dieci di sera e le sette del mattino.</p>
<p>È il numero più facile da sottovalutare di tutto il progetto. Non dice che l’automazione è veloce, dice che <strong>quasi metà delle richieste arriva quando non c’è nessuno a leggerle</strong>. Sono le sere e le domeniche in cui uno si mette a guardare i conti, e proprio lì si decide a scrivere.</p></section>
<section id="un-numero-di-telefono-sotto-un-post-e-un-problema-non-un-contatto"><h2>Un numero di telefono sotto un post è un problema, non un contatto</h2>
<p>Capita spesso: la persona scrive il suo numero di telefono dentro il commento, in chiaro, sotto l’inserzione. Vuole essere richiamata. Nel frattempo quel numero lo legge chiunque passi di lì.</p>
<p>L’automazione lo tratta come un incidente da chiudere, non come un contatto da incassare: <strong>quando un commento contiene un numero di telefono o un dettaglio delicato, lo nasconde</strong> e sposta la conversazione in privato. Vale sotto le inserzioni e sotto i post organici, su Facebook e su Instagram.</p>
<p>Sotto i commenti c’è anche un’attesa voluta di tre minuti prima della risposta pubblica. Non è lentezza: una risposta che compare nello stesso secondo in cui uno ha finito di scrivere dice a tutti che sotto c’è una macchina.</p></section>
<section id="quando-passa-a-una-persona-e-perche"><h2>Quando passa a una persona, e perché</h2>
<p><strong>111 conversazioni su 2.329</strong>, meno di una su venti, sono passate a una persona del team. Tutto il resto lo ha chiuso l’automazione da sola.</p>
<p>Il controllo però resta al cliente, ed è il pezzo che in una demo non si vede mai: dal pannello di controllo l’associazione <strong>spegne l’automazione su una singola conversazione</strong> e continua a mano, senza toccare le altre. Da quel momento quella chat è sua e il bot non ci scrive più.</p>
<p>C’è poi una regola che sembra una banalità e non lo è: <strong>sul compenso non si gira intorno.</strong> All’associazione un compenso spetta, in percentuale sul recuperato. Nei commenti la domanda «quanto mi costa» arriva ogni giorno, spesso con tono ostile. La risposta dice che perizia e ricorso sono gratuiti e che si paga solo se il rimborso arriva, e non prova a spostare la domanda in privato. Su un pubblico che di promesse ne ha già sentite troppe, una risposta evasiva vale meno di zero.</p>
<figure class="scatto"><img class="scatto-img" src="/assets/images/casi/adifesa-1-facebook-commenti.png" alt="Thread di commenti sotto un post di ADifesa: alla domanda «È a pagamento?» la Pagina risponde in pubblico che perizia e ricorso sono gratuiti e che si paga un compenso solo se il rimborso arriva." width="779" height="664" loading="lazy" decoding="async"><figcaption>Commenti veri sotto un post del 18 settembre 2026. La domanda sul costo arriva in pubblico, e la risposta resta in pubblico. Nomi e foto sono distrutti nei pixel.</figcaption></figure></section>
<section id="instagram-e-arrivato-dopo-e-si-vede"><h2>Instagram è arrivato dopo, e si vede</h2>
<p>Il progetto è nato su Facebook. I messaggi diretti di Instagram hanno richiesto un passaggio in più: <strong>cinque permessi da far approvare a Meta</strong>, ognuno con un video dimostrativo.</p>
<p>Il primo invio, a maggio, non è passato. I cinque video sono stati rigirati il 28 maggio con un metodo diverso, mostrando la catena dell’identità fra il portale Meta e il sistema, e questa volta è andata. Nel mezzo c’è stato un dettaglio che vale da solo il racconto: <strong>Meta chiedeva la dimostrazione di una funzione che nelle sue API non esiste</strong>, cioè modificare un commento su Instagram. Si può creare, nascondere, cancellare, non modificare. La dimostrazione è stata riscritta su quello che l’API fa davvero.</p>
<p>Da lì si vede l’effetto nei dati, sui contatti qualificati arrivati da Instagram:</p>
<div class="tab motivi"><table><thead><tr><th scope="col">Mese</th><th scope="col">Contatti</th></tr></thead><tbody><tr><td>Maggio</td><td class="num"><span class="barra" style="--f:0.051" aria-hidden="true"></span>6</td></tr><tr><td>Giugno</td><td class="num"><span class="barra" style="--f:0.248" aria-hidden="true"></span>29</td></tr><tr><td>Luglio</td><td class="num"><span class="barra" style="--f:1.000" aria-hidden="true"></span>117</td></tr><tr><td>Agosto</td><td class="num"><span class="barra" style="--f:0.188" aria-hidden="true"></span>22</td></tr><tr><td>Settembre, al 16</td><td class="num"><span class="barra" style="--f:0.051" aria-hidden="true"></span>6</td></tr></tbody></table></div>
<figure class="scatto"><img class="scatto-img" src="/assets/images/casi/adifesa-3-instagram-dm.png" alt="Conversazione in un messaggio diretto di Instagram: la persona chiede una consulenza, l&#x27;assistente chiede telefono, email e orari di richiamo, e li riceve in tre messaggi." width="953" height="722" loading="lazy" decoding="async"><figcaption>Messaggio diretto di Instagram, 24 agosto 2026. Le bolle viola sono il modo in cui la casella di Meta distingue Instagram da Messenger. Qui la scheda si completa in tre risposte: prima telefono e orari, poi l’email.</figcaption></figure></section>
<section id="il-post-che-costava-diciotto-dollari-al-giorno"><h2>Il post che costava diciotto dollari al giorno</h2>
<p>A luglio un contenuto dell’associazione è diventato virale nel modo peggiore: migliaia di commenti di sfogo politico, nessuno dei quali era un caso da seguire. L’automazione li leggeva uno per uno e li classificava correttamente come non pertinenti, <strong>ma per capirlo doveva prima chiamare il modello</strong>. Circa diciotto dollari al giorno bruciati per rispondere a nessuno.</p>
<p>La soluzione non è stata alzare i filtri, è stato un contatore. Ogni post tiene il conto dei commenti visti e di quanti sono risultati spam: superata una soglia, <strong>quel singolo post viene messo in sordina</strong> e i commenti non arrivano più al modello. Nella finestra osservata i post seguiti sono <strong>257</strong>, quelli messi in sordina <strong>37</strong>.</p>
<p>Un post in sordina non diventa cieco: le parole che indicano un prodotto vero, come il nome di una finanziaria o «cessione del quinto», passano comunque. Il controllo prima di metterlo in produzione lo abbiamo fatto sui commenti veri, non su esempi inventati: nessun caso buono perso su trentacinque provati, e i dieci casi buoni riconosciuti tutti e dieci.</p></section>
<section id="cosa-abbiamo-sbagliato-e-sistemato"><h2>Cosa abbiamo sbagliato, e sistemato</h2>
<p>Se raccontassimo solo le cose che hanno funzionato, sarebbe pubblicità.</p>
<ul><li><strong>«Mi trattengono il quinto dello stipendio» finiva nello spam.</strong> Il filtro scartava chi parlava di una frazione dello stipendio, per evitare gli sfoghi generici. Ma il quinto è letteralmente un quinto: era il prodotto principale dell’associazione, scambiato per rumore.</li><li><strong>Chi ricommentava riceveva due volte il messaggio di apertura.</strong> Una persona già in chat, che tornava a scrivere sotto un’inserzione, si vedeva arrivare un secondo «come possiamo aiutarla?». Ora se la conversazione è già aperta il secondo messaggio non parte.</li><li><strong>I reel condivisi in privato facevano ripartire il bot.</strong> Instagram manda un video condiviso come un messaggio senza testo, e l’automazione rispondeva a ogni condivisione. Adesso un allegato senza parole non riceve risposta.</li><li><strong>Su Instagram i contatti si chiamavano tutti «Utente c168f1».</strong> Il nome veniva letto da un campo che per Instagram non esiste. Sistemato e recuperati i nomi vecchi, da 33 senza nome a 4.</li></ul></section>
<section id="quanti-di-quei-contatti-diventano-clienti"><h2>Quanti di quei contatti diventano clienti</h2>
<p>Il nostro database si ferma alla scheda completa. Cosa succede dopo, quando la consulente chiama, lo sa solo l’associazione: gliel’abbiamo chiesto.</p>
<p>La risposta: <strong>8 schede complete su 10 diventano clienti</strong>, con almeno una pratica aperta.</p>
<p>È un numero loro, che esce dal loro sistema e non dal nostro, e lo riportiamo come ce l’hanno detto. Vale la pena leggerlo per quello che è: non l’80% di chi commenta, ma l’80% di chi è arrivato in fondo alla conversazione lasciando nome, telefono, email e prodotto.</p></section>
<section id="cosa-questi-numeri-non-dicono"><h2>Cosa questi numeri non dicono</h2>
<p>Non contiamo il lavoro delle persone dopo il passaggio di mano, perché da quel punto la conversazione continua dentro gli strumenti di Meta e non nel nostro sistema. E l’esito della verifica di eleggibilità non viene registrato come tale: la decisione la prende la consulente, con i documenti in mano.</p>
<p>Quanti rimborsi siano poi arrivati, e per quali cifre, non è un dato nostro e non lo mettiamo qui. Un caso studio che promette il fatturato senza avere il dato del fatturato è un annuncio travestito.</p></section>
<section id="domande-frequenti"><h2>Domande frequenti</h2>
<div class="faq"><details open><summary>Quante conversazioni ha gestito l’automazione?</summary><p>Dal 1° maggio al 16 settembre 2026 ha gestito 2.329 conversazioni fra commenti e messaggi privati su Facebook e Instagram, con 1.794 persone diverse. Ne sono usciti 1.033 contatti qualificati e 524 schede complete di nome, telefono ed email.</p></details><details><summary>Risponde anche ai commenti pubblici o solo ai messaggi privati?</summary><p>A entrambi. Sotto il commento pubblico risponde dopo un’attesa voluta di tre minuti, e in parallelo apre la conversazione privata. Nella finestra osservata ha scritto 1.262 risposte pubbliche e 1.676 messaggi privati.</p></details><details><summary>Cosa succede se qualcuno scrive il suo numero di telefono in un commento?</summary><p>Il commento viene nascosto e la conversazione si sposta in privato. Un numero di telefono in chiaro sotto un’inserzione è un rischio per chi lo ha scritto, non un contatto da raccogliere.</p></details><details><summary>Quando interviene una persona?</summary><p>Quando serve, e sempre per scelta del cliente: dal pannello di controllo l’automazione si spegne sulla singola conversazione e il team continua a mano. È successo con 111 conversazioni su 2.329, meno di una su venti.</p></details><details><summary>Quanti di quei contatti diventano clienti?</summary><p>Secondo l’associazione, 8 schede complete su 10 diventano clienti con almeno una pratica aperta. È un dato loro, dal loro sistema: il nostro database si ferma alla scheda completa, cioè nome, telefono, email e prodotto.</p></details><details><summary>Quanto ci vuole a metterla in piedi?</summary><p>Dipende da quanto sono definite le regole. La parte lunga non è il software, è scrivere nero su bianco quando un caso rientra e quando no: qui sono dieci regole con finestre di anni, importi minimi e nomi di finanziarie. Per i messaggi diretti di Instagram va messa in conto anche l’approvazione dei permessi da parte di Meta.</p></details></div></section>
<section id="per-chiudere"><h2>Per chiudere</h2>
<p>Se fai campagne su Meta, sotto le tue inserzioni c’è già una coda di persone che ti stanno chiedendo qualcosa. La domanda non è se rispondere in automatico, è <strong>se le tue regole sono scritte abbastanza bene</strong> perché qualcuno possa rispondere al posto tuo.</p>
<p>Se vuoi vedere come lavoriamo prima di parlarne, qui trovi <a href="/it/ai-automations">come costruiamo le automazioni</a>.</p>
<div class="cta"><a class="btn" href="https://api.leadconnectorhq.com/widget/bookings/automis-it" target="_blank" rel="noopener">Prenota una chiamata</a><p>Trenta minuti, e ti diciamo da dove partiremmo noi.</p></div></section>
</article>`;
