/* Generato da build.py del secondo cervello (--sito). Non modificare a mano:
   il testo si cambia in testo-articolo.md, lo stile in stile.css. */
export default `<div class="hero">
  <nav class="briciole" aria-label="Breadcrumb"><ol><li><a href="/pt">Home</a></li><li><a href="/pt/use-cases">Casos de estudo</a></li><li aria-current="page">Clínica Santa Maria dos Olivais</li></ol></nav>
  <h1>7 meses ao telefone de uma clínica dentária</h1>
  <p class="sub">872 chamadas, 114 marcações e 527 telefonemas resolvidos pelo assistente sem passar pela receção.</p>
  <div class="clinica"><span class="tile"><img src="/assets/images/client-logos/clinica-santa-maria.png" alt="Clínica Santa Maria dos Olivais" width="67" height="48"></span><div><b>Clínica Santa Maria dos Olivais</b><span class="dove">Clínica dentária · Lisboa</span></div></div>
  <figure class="curva" style="--n:8" role="img" aria-label="Gráfico das chamadas recebidas pelo assistente em cada mês, de fevereiro a setembro de 2026: fev 81, mar 45, abr 50, mai 34, jun 154, jul 168, ago 275, set 65"><figcaption class="curva-testa"><span>Chamadas por mês</span><span class="tot">872 no total</span></figcaption><div class="barre"><div class="col" style="--h:29.5%;--i:0"><span class="v">81</span><span class="b"></span></div><div class="col" style="--h:16.4%;--i:1"><span class="v">45</span><span class="b"></span></div><div class="col" style="--h:18.2%;--i:2"><span class="v">50</span><span class="b"></span></div><div class="col" style="--h:12.4%;--i:3"><span class="v">34</span><span class="b"></span></div><div class="col dopo svolta" style="--h:56.0%;--i:4"><span class="svolta-et">Junho · Google Maps</span><span class="v">154</span><span class="b"></span></div><div class="col dopo" style="--h:61.1%;--i:5"><span class="v">168</span><span class="b"></span></div><div class="col dopo" style="--h:100.0%;--i:6"><span class="v">275</span><span class="b"></span></div><div class="col dopo" style="--h:23.6%;--i:7"><span class="v">65</span><span class="b"></span></div></div><div class="mesi" aria-hidden="true"><span>fev</span><span>mar</span><span>abr</span><span>mai</span><span>jun</span><span>jul</span><span>ago</span><span>set</span></div><div class="anni" aria-hidden="true"><span>2026</span></div><p class="nota">Desde junho o número do assistente está no Google Maps. Setembro até ao dia 9.</p></figure>
  <aside class="breve"><span class="et">Em resumo</span><p>De 1 de fevereiro a 9 de setembro de 2026, um assistente de voz da Automis atendeu 872 chamadas da Clínica Santa Maria dos Olivais, uma clínica dentária de Lisboa com uma só rececionista. 527 ficaram resolvidas sem passar por ela e 114 terminaram com uma marcação na agenda. No início atendia só o número dos anúncios: desde junho, quando a diretora passou a confiar, atende o número que está no Google Maps.</p></aside>
</div>
<article class="corpo">
<section id="o-ponto-de-partida"><h2>O ponto de partida</h2>
<p>A Clínica Santa Maria dos Olivais é uma clínica dentária de Lisboa: seis dentistas, cada um com as suas especialidades e os seus dias, e uma só rececionista. Numa clínica o telefone é tudo: quem liga e não é atendido muitas vezes não volta a ligar, tenta o dentista seguinte.</p>
<p>Quantas chamadas se perdiam antes ninguém contava. A estimativa da clínica é uma dezena por dia.</p>
<p>O problema não era a tecnologia, era a confiança. A diretora não confiava em pôr uma inteligência artificial ao telefone com os seus pacientes, e não lhe faltava razão: se o assistente se engana, quem fica mal é ela.</p></section>
<section id="comecamos-pequeno"><h2>Começámos pequeno</h2>
<p>Não tentámos convencê-la com uma apresentação. No início o assistente de voz atendia <strong>só o número dos anúncios</strong>: quem liga para ali já viu a publicidade e sabe o que procura. Se alguma coisa corresse mal, desligávamo-lo numa tarde sem que ninguém na clínica desse por isso.</p></section>
<section id="depois-passou-a-confiar"><h2>Depois passou a confiar</h2>
<p>Em maio o assistente atendia 34 chamadas por mês. Em agosto, 275.</p>
<p>Não ficou oito vezes melhor. Em junho a diretora passou a confiar em nós e <strong>entregou tudo ao sistema</strong>: o número do assistente foi para o Google Maps, o número que encontra quem procura a clínica.</p></section>
<section id="os-numeros"><h2>Os números</h2>
<p class="nota"><em>Dados de produção, de 1 de fevereiro a 9 de setembro de 2026.</em></p>
<figure class="ripartizione"><div class="barra-tot" role="img" aria-label="527 Resolvidas pelo assistente, 223 Passadas à receção, 122 Desligadas nos primeiros 10 segundos"><span class="seg s0" style="--p:60.44%"></span><span class="seg s1" style="--p:25.57%"></span><span class="seg s2" style="--p:13.99%"></span></div><ul><li><span class="pal s0"></span><b>527</b><span>Resolvidas pelo assistente</span><span class="perc">60%</span></li><li><span class="pal s1"></span><b>223</b><span>Passadas à receção</span><span class="perc">26%</span></li><li><span class="pal s2"></span><b>122</b><span>Desligadas nos primeiros 10 segundos</span><span class="perc">14%</span></li></ul></figure>
<div class="tab"><table><tbody><tr><td>Chamadas recebidas pelo assistente</td><td><strong>872</strong></td></tr><tr><td>Resolvidas pelo assistente, sem passar pela receção</td><td><strong>527</strong></td></tr><tr><td>Passadas à receção</td><td><strong>223</strong></td></tr><tr><td>Desligadas nos primeiros 10 segundos</td><td><strong>122</strong></td></tr><tr><td>Marcações feitas</td><td><strong>114</strong></td></tr><tr><td>Fora de horas ou com outra chamada a decorrer</td><td><strong>193</strong> (22%)</td></tr><tr><td>Pessoas diferentes com quem falou</td><td><strong>385</strong></td></tr><tr><td>Duração média de uma conversa</td><td><strong>1 minuto e 37 segundos</strong></td></tr><tr><td>Horas de telefone tratadas</td><td><strong>20,2</strong></td></tr></tbody></table></div></section>
<section id="seis-linguas-e-muda-sozinho"><h2>Seis línguas, e muda sozinho</h2>
<p>Lisboa é uma capital multicultural, e só o português não chega para quem liga. O assistente atende em <strong>português europeu, inglês, italiano, espanhol, francês e alemão</strong>.</p>
<p>Conta mais como o faz. A chamada começa sempre em português: se quem liga passa para outra língua, ou a pede, o assistente <strong>muda de língua logo na resposta seguinte</strong>. Não o anuncia, não pede autorização e não passa a chamada a ninguém.</p></section>
<section id="encontrar-um-horario-livre-ja-era-um-trabalho"><h2>Encontrar um horário livre já era um trabalho</h2>
<p>Seis dentistas, e nenhum a tempo inteiro. Trabalham em meios dias e cada um faz coisas diferentes: a ortodontia só <strong>à quarta-feira</strong>, o dentista das crianças só <strong>à terça</strong>, as desvitalizações à terça, à quinta e à sexta, e a implantologia segue os horários da diretora.</p>
<figure class="settimana"><table><thead><tr><th scope="col"><span class="sr-only">Tratamento</span></th><th scope="col">seg</th><th scope="col">ter</th><th scope="col">qua</th><th scope="col">qui</th><th scope="col">sex</th></tr></thead><tbody><tr><th scope="row">Ortodontia</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td></tr><tr><th scope="row">Dentista das crianças</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td></tr><tr><th scope="row">Desvitalizações</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto on" role="img" aria-label="está"></span></td></tr><tr><th scope="row">Implantologia</th><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">não está</span></td><td><span class="punto on" role="img" aria-label="está"></span></td><td><span class="punto on" role="img" aria-label="está"></span></td></tr></tbody></table><figcaption>Quem está e quando, de segunda a sexta. Todos em meios dias.</figcaption></figure>
<p>Quer dizer que alguns tratamentos <strong>existem num só dia da semana</strong>. Para encontrar o primeiro horário livre não basta olhar para a agenda: têm de coincidir quatro coisas, o tratamento, o dentista que o faz, o dia em que esse dentista está e uma hora ainda livre nesse dia.</p>
<p><strong>E antes disso o assistente tem de perceber do que se fala.</strong> Ao telefone ninguém diz «endodontia»: diz que tem dores, que lhe caiu uma coroa, que quer o aparelho ou uma limpeza. Os tipos de tratamento são vinte e um, e têm de ser reconhecidos pela forma como as pessoas falam, porque é essa palavra que decide a que dentista se vai. Foi precisamente aqui que o sistema falhou uma vez: a palavra «avaliação» era demasiado vaga e mandava os pacientes ao dentista errado.</p></section>
<section id="como-procura-um-horario"><h2>Como procura um horário</h2>
<ul><li>Propõe <strong>sempre duas horas</strong>: nunca uma só, nunca uma lista.</li><li>Se não servirem, procura outras duas <strong>mais à frente</strong>, e nunca repete as que já foram recusadas.</li><li>Se a agenda devolver as mesmas horas, horas anteriores ou nada, considera isso uma <strong>falha lógica</strong> e para ao fim de duas tentativas.</li><li>A partir daí não insiste: dentro do horário passa a chamada à receção, fora de horas propõe ligar de volta.</li></ul>
<p>Um sistema que interroga uma agenda cheia até encontrar alguma coisa é facílimo de escrever, e é o pior de pôr ao telefone.</p></section>
<section id="as-urgencias-onde-e-preciso-dizer-uma-coisa-incomoda"><h2>As urgências, onde é preciso dizer uma coisa incómoda</h2>
<p>A clínica trabalha só por marcação e <strong>não tem vagas para urgências</strong>. Quando o assistente percebe que quem liga tem dores fortes, um dente partido, um inchaço ou uma hemorragia, não promete nada: reconhece o problema numa frase, explica que a primeira vaga tanto pode ser amanhã como daqui a uma semana, e propõe dois caminhos, o primeiro horário livre ou a receção, se a clínica estiver aberta.</p>
<p>Prometer uma vaga imediata a quem tem dores é fácil de programar e impossível de cumprir. É a diferença entre uma demonstração e um sistema a trabalhar há sete meses.</p></section>
<section id="quando-passa-a-chamada-a-rececao-e-porque"><h2>Quando passa a chamada à receção, e porquê</h2>
<p>Cerca de uma chamada em quatro, <strong>223 em 872</strong>, acaba na receção. Não é uma derrota: <strong>o assistente não passa a chamada a quem a pede.</strong> Primeiro pergunta o motivo, e se for uma coisa que sabe resolver tenta resolvê-la. Só passa a chamada se a pessoa insistir.</p>
<div class="tab motivi"><table><thead><tr><th scope="col">Motivo</th><th scope="col">Chamadas</th></tr></thead><tbody><tr><td>Insiste em falar com uma pessoa, depois de o assistente ter tentado</td><td class="num"><span class="barra" style="--f:1.000" aria-hidden="true"></span><strong>111</strong></td></tr><tr><td>Limpeza de implantes: por regra da clínica só a receção marca</td><td class="num"><span class="barra" style="--f:0.234" aria-hidden="true"></span>26</td></tr><tr><td>Não quer que a chamada seja gravada</td><td class="num"><span class="barra" style="--f:0.225" aria-hidden="true"></span>25</td></tr><tr><td>Urgência ou dores</td><td class="num"><span class="barra" style="--f:0.189" aria-hidden="true"></span>21</td></tr><tr><td>Motivo não classificável</td><td class="num"><span class="barra" style="--f:0.360" aria-hidden="true"></span>40</td></tr></tbody></table></div>
<p class="nota"><em>A classificação é automática, feita sobre os resumos das chamadas: deve ser lida como indicativa.</em></p>
<p>Tudo o resto trata sozinho, <strong>incluindo cancelar e remarcar</strong>, que são as duas coisas que normalmente se pensa terem de passar por uma pessoa.</p>
<p>Há ainda um caso que existe mas não se consegue contar: o assistente propõe horas, a pessoa recusa-as uma a uma, e ao fim de algumas tentativas a chamada passa à receção. Nos resumos aparece demasiado poucas vezes para lhe dar um número.</p></section>
<section id="o-que-corremos-mal-e-corrigimos"><h2>O que corremos mal, e corrigimos</h2>
<p>Se contássemos só o que correu bem, era publicidade.</p>
<ul><li>A palavra «avaliação» no menu das marcações era demasiado vaga, e o assistente marcava com o dentista errado. Demos por isso à segunda reclamação.</li><li>Quando alguém pedia para falar com uma pessoa, a frase com que o assistente o tranquilizava dizia que era uma inteligência artificial, e levantava exatamente a dúvida que queria tirar. Reescrevemo-la de forma neutra.</li><li>A última atualização entrou à terceira tentativa: as duas primeiras foram chumbadas pelos testes, antes de chegarem a chamadas reais.</li></ul></section>
<section id="quanto-fez-ganhar-numa-estimativa"><h2>Quanto fez ganhar, numa estimativa</h2>
<p>A faturação real só a clínica a conhece. Uma estimativa honesta, porém, é possível: para cada marcação o assistente registou o tratamento e se o paciente era novo, e a tabela de preços diz quanto custa cada um.</p>
<figure class="stima"><div class="passo"><span class="et">Marcações feitas, a preço de tabela</span><span class="traccia"><span class="pezzo primo" style="--da:0.00%;--l:9.07%"></span></span><span class="val">5.200 €</span></div><div class="passo"><span class="et">Tratamentos pedidos pelos pacientes novos</span><span class="traccia"><span class="pezzo" style="--da:9.07%;--l:2.40%"></span></span><span class="val">+1.400 €</span></div><div class="passo"><span class="et">Implantes, se metade das 23 consultas virar tratamento</span><span class="traccia"><span class="pezzo" style="--da:11.47%;--l:44.27%"></span></span><span class="val">+25.400 €</span></div><div class="passo totale"><span class="et">Total estimado em sete meses</span><span class="traccia"><span class="pezzo pieno" style="--da:0%;--l:55.74%"></span><span class="pezzo fantasma" style="--da:55.74%;--l:44.26%"></span></span><span class="val">cerca de 32.000 €</span></div><p class="stima-max">Se todas as consultas de implantes virassem tratamento: cerca de 57.000 €</p></figure>
<p class="nota"><em>Estimativa a preços de tabela. As consultas de implantes valem a média dos tratamentos do programa da clínica, cerca de 2.200 € cada: de 745 € por um implante unitário a 4.800 € por uma arcada completa. Primeira consulta dos pacientes novos a 20 €, e não foram descontadas as faltas.</em></p>
<p>Para nós o número que mais conta é outro: <strong>23 primeiras consultas de implantes em sete meses</strong>. É a parte mais cara da tabela, e basta que uma vire uma arcada completa para valer quase 5.000 euros.</p></section>
<section id="perguntas-frequentes"><h2>Perguntas frequentes</h2>
<div class="faq"><details open><summary>Quantas chamadas tratou o assistente de voz?</summary><p>De 1 de fevereiro a 9 de setembro de 2026 atendeu 872 chamadas: 527 ficaram resolvidas sem passar pela receção, 223 passaram à rececionista e 122 foram desligadas nos primeiros 10 segundos. As marcações feitas são 114.</p></details><details><summary>Em que línguas atende?</summary><p>Em português europeu, inglês, italiano, espanhol, francês e alemão. A chamada começa em português e, se quem liga usar outra língua, o assistente muda na resposta seguinte, sem passar a chamada a ninguém.</p></details><details><summary>O que faz se um paciente ligar com uma urgência?</summary><p>A clínica não tem vagas para urgências, e o assistente não promete nenhuma. Reconhece o problema, explica que a primeira vaga tanto pode ser amanhã como daqui a uma semana e propõe o primeiro horário livre ou a receção, se a clínica estiver aberta.</p></details><details><summary>Quando passa a chamada a uma pessoa?</summary><p>Quando quem liga insiste em falar com uma pessoa depois de o assistente ter tentado resolver, para limpezas de implantes, quando alguém não quer a chamada gravada e nas urgências. Aconteceu em 223 chamadas em 872.</p></details><details><summary>Por onde vale a pena começar com um assistente de voz?</summary><p>Para nós por uma linha só, como fizemos aqui com o número dos anúncios: se alguma coisa correr mal desliga-se numa tarde, e se resultar alarga-se.</p></details></div></section>
<section id="para-terminar"><h2>Para terminar</h2>
<p>Se tem uma clínica ou um consultório, para nós a pergunta certa não é se uma inteligência artificial pode atender o telefone. É de que parte do telefone a pôr a começar.</p>
<p>Se quiser perceber como trabalha antes de falarmos, aqui fica <a href="/pt/voice-ai">como funciona o assistente de voz</a>.</p>
<div class="cta"><a class="btn" href="https://api.leadconnectorhq.com/widget/bookings/pt-automis" target="_blank" rel="noopener">Marcar uma chamada</a><p>Trinta minutos, e dizemos-lhe por onde começaríamos.</p></div></section>
</article>`;
