/* Generato da build.py del secondo cervello (--sito). Non modificare a mano:
   il testo si cambia in testo-articolo.md, lo stile in stile.css. */
export default `<div class="hero">
  <nav class="briciole" aria-label="Breadcrumb"><ol><li><a href="/it">Home</a></li><li><a href="/it/use-cases">Casi studio</a></li><li aria-current="page">Clínica Santa Maria dos Olivais</li></ol></nav>
  <h1>7 mesi al telefono di una clinica dentale</h1>
  <p class="sub">872 chiamate, 114 appuntamenti e 527 telefonate chiuse dall’assistente senza passare dalla segretaria.</p>
  <div class="clinica"><span class="tile"><img src="/assets/images/client-logos/clinica-santa-maria.png" alt="Clínica Santa Maria dos Olivais" width="67" height="48"></span><div><b>Clínica Santa Maria dos Olivais</b><span class="dove">Studio dentistico · Lisbona</span></div></div>
  <figure class="curva" style="--n:8" role="img" aria-label="Grafico delle chiamate arrivate all'assistente ogni mese, da febbraio a settembre 2026: feb 81, mar 45, apr 50, mag 34, giu 154, lug 168, ago 275, set 65"><figcaption class="curva-testa"><span>Chiamate al mese</span><span class="tot">872 in totale</span></figcaption><div class="barre"><div class="col" style="--h:29.5%;--i:0"><span class="v">81</span><span class="b"></span></div><div class="col" style="--h:16.4%;--i:1"><span class="v">45</span><span class="b"></span></div><div class="col" style="--h:18.2%;--i:2"><span class="v">50</span><span class="b"></span></div><div class="col" style="--h:12.4%;--i:3"><span class="v">34</span><span class="b"></span></div><div class="col dopo svolta" style="--h:56.0%;--i:4"><span class="svolta-et">Giugno · Google Maps</span><span class="v">154</span><span class="b"></span></div><div class="col dopo" style="--h:61.1%;--i:5"><span class="v">168</span><span class="b"></span></div><div class="col dopo" style="--h:100.0%;--i:6"><span class="v">275</span><span class="b"></span></div><div class="col dopo" style="--h:23.6%;--i:7"><span class="v">65</span><span class="b"></span></div></div><div class="mesi" aria-hidden="true"><span>feb</span><span>mar</span><span>apr</span><span>mag</span><span>giu</span><span>lug</span><span>ago</span><span>set</span></div><div class="anni" aria-hidden="true"><span>2026</span></div><p class="nota">Da giugno il numero dell’assistente è su Google Maps. Settembre fino al 9.</p></figure>
  <aside class="breve"><span class="et">In breve</span><p>Dal 1° febbraio al 9 settembre 2026 un assistente vocale di Automis ha risposto a 872 chiamate della Clínica Santa Maria dos Olivais, uno studio dentistico di Lisbona con una segretaria sola. 527 si sono chiuse senza passare da lei e 114 sono finite con un appuntamento in agenda. All’inizio rispondeva solo al numero degli annunci: da giugno, quando la titolare si è fidata, risponde al numero su Google Maps.</p></aside>
</div>
<article class="corpo">
<section id="il-punto-di-partenza"><h2>Il punto di partenza</h2>
<p>La Clínica Santa Maria dos Olivais è uno studio dentistico di Lisbona: sei dentisti, ognuno con le sue specializzazioni e i suoi giorni, e una segretaria sola. Per uno studio il telefono è tutto: chi chiama e non trova risposta spesso non richiama, e prova dal dentista successivo.</p>
<p>Quante chiamate si perdessero prima non lo contava nessuno. La stima della clinica è una decina al giorno.</p>
<p>Il problema non era la tecnologia, era la fiducia. La titolare non si fidava a mettere un’intelligenza artificiale al telefono con i suoi pazienti, e come darle torto: se l’assistente sbaglia, la brutta figura la fa lei.</p></section>
<section id="siamo-partiti-in-piccolo"><h2>Siamo partiti in piccolo</h2>
<p>Non abbiamo provato a convincerla con una presentazione. All’inizio l’assistente vocale rispondeva <strong>solo al numero degli annunci</strong>: chi chiama lì ha già visto la pubblicità e sa cosa cerca. Se qualcosa fosse andato storto, lo avremmo spento in un pomeriggio senza che in clinica se ne accorgesse nessuno.</p></section>
<section id="poi-si-e-fidata"><h2>Poi si è fidata</h2>
<p>A maggio l’assistente rispondeva a 34 chiamate al mese. Ad agosto a 275.</p>
<p>Non è diventato otto volte più bravo. A giugno la titolare si è fidata di noi e <strong>si è affidata completamente al sistema</strong>: il numero dell’assistente è finito su Google Maps, cioè quello che trova chiunque cerchi la clinica.</p></section>
<section id="i-numeri"><h2>I numeri</h2>
<p class="nota"><em>Dati di produzione, dal 1° febbraio al 9 settembre 2026.</em></p>
<figure class="ripartizione"><div class="barra-tot" role="img" aria-label="527 Chiuse dall&#x27;assistente, 223 Passate alla segretaria, 122 Riattaccate nei primi 10 secondi"><span class="seg s0" style="--p:60.44%"></span><span class="seg s1" style="--p:25.57%"></span><span class="seg s2" style="--p:13.99%"></span></div><ul><li><span class="pal s0"></span><b>527</b><span>Chiuse dall’assistente</span><span class="perc">60%</span></li><li><span class="pal s1"></span><b>223</b><span>Passate alla segretaria</span><span class="perc">26%</span></li><li><span class="pal s2"></span><b>122</b><span>Riattaccate nei primi 10 secondi</span><span class="perc">14%</span></li></ul></figure>
<div class="tab"><table><tbody><tr><td>Chiamate arrivate all’assistente</td><td><strong>872</strong></td></tr><tr><td>Chiuse dall’assistente, senza passare dalla segretaria</td><td><strong>527</strong></td></tr><tr><td>Passate alla segretaria</td><td><strong>223</strong></td></tr><tr><td>Riattaccate nei primi 10 secondi</td><td><strong>122</strong></td></tr><tr><td>Appuntamenti presi</td><td><strong>114</strong></td></tr><tr><td>Arrivate fuori orario o con un’altra chiamata in corso</td><td><strong>193</strong> (22%)</td></tr><tr><td>Persone diverse con cui ha parlato</td><td><strong>385</strong></td></tr><tr><td>Durata media di una conversazione</td><td><strong>1 minuto e 37 secondi</strong></td></tr><tr><td>Ore di telefono gestite</td><td><strong>20,2</strong></td></tr></tbody></table></div></section>
<section id="sei-lingue-e-cambia-da-solo"><h2>Sei lingue, e cambia da solo</h2>
<p>Lisbona è una capitale multiculturale, e il portoghese da solo non basta a coprire chi chiama. L’assistente risponde in <strong>portoghese europeo, inglese, italiano, spagnolo, francese e tedesco</strong>.</p>
<p>Conta di più come lo fa. La chiamata parte sempre in portoghese: se chi chiama passa a un’altra lingua, o la chiede, l’assistente <strong>cambia lingua subito, nella risposta successiva</strong>. Non lo annuncia, non chiede il permesso e non passa la chiamata a nessuno.</p></section>
<section id="trovare-un-posto-libero-era-gia-un-lavoro"><h2>Trovare un posto libero era già un lavoro</h2>
<p>Sei dentisti, e nessuno a tempo pieno. Lavorano a mezze giornate e ognuno fa cose diverse: l’ortodonzia c’è <strong>solo il mercoledì</strong>, il dentista per i bambini <strong>solo il martedì</strong>, le devitalizzazioni il martedì, il giovedì e il venerdì, l’implantologia segue gli orari della direttrice.</p>
<figure class="settimana"><table><thead><tr><th scope="col"><span class="sr-only">Trattamento</span></th><th scope="col">lun</th><th scope="col">mar</th><th scope="col">mer</th><th scope="col">gio</th><th scope="col">ven</th></tr></thead><tbody><tr><th scope="row">Ortodonzia</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td></tr><tr><th scope="row">Dentista per bambini</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td></tr><tr><th scope="row">Devitalizzazioni</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td></tr><tr><th scope="row">Implantologia</th><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">non c'è</span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td><td><span class="punto on" role="img" aria-label="c'è"></span></td></tr></tbody></table><figcaption>Chi c’è e quando, dal lunedì al venerdì. Tutti a mezze giornate.</figcaption></figure>
<p>Vuol dire che alcuni trattamenti <strong>esistono in un solo giorno della settimana</strong>. Per trovare il primo posto libero non basta guardare l’agenda: devono combaciare quattro cose, cioè il trattamento, il dentista che lo fa, il giorno in cui c’è e un orario ancora libero quel giorno.</p>
<p><strong>E prima ancora l’assistente deve capire di cosa si parla.</strong> Al telefono nessuno dice «endodonzia»: dice che ha male, che gli è caduta una capsula, che vuole l’apparecchio o una pulizia. I tipi di trattamento sono ventuno, e vanno riconosciuti da come parla la gente, perché è quella parola a decidere da quale dentista si va. Proprio qui il sistema ha sbagliato una volta: la parola «valutazione» era troppo generica e mandava i pazienti dal dentista sbagliato.</p></section>
<section id="come-cerca-un-posto"><h2>Come cerca un posto</h2>
<ul><li>Propone <strong>sempre due orari</strong>: mai uno solo, mai una lista.</li><li>Se non vanno bene, ne cerca altri due <strong>più avanti nel tempo</strong>, e non ripropone quelli già scartati.</li><li>Se l’agenda gli restituisce gli stessi orari, orari precedenti o niente, lo considera un <strong>fallimento logico</strong> e si ferma dopo due tentativi.</li><li>A quel punto non insiste: in orario passa la chiamata alla segretaria, fuori orario propone di essere richiamati.</li></ul>
<p>Un sistema che interroga un’agenda piena finché non trova qualcosa è facilissimo da scrivere, ed è il peggiore da mettere al telefono.</p></section>
<section id="le-urgenze-dove-bisogna-dire-una-cosa-scomoda"><h2>Le urgenze, dove bisogna dire una cosa scomoda</h2>
<p>La clinica lavora solo su appuntamento e <strong>non ha posti per le urgenze</strong>. Quando l’assistente capisce che chi chiama ha un dolore forte, un dente rotto, un gonfiore o un sanguinamento, non promette niente: lo riconosce in una frase, spiega che il primo posto potrebbe essere domani come fra una settimana, e propone due strade, il primo posto libero oppure la segretaria, se la clinica è aperta.</p>
<p>Promettere un posto subito a chi ha male è facile da programmare e impossibile da mantenere. È la differenza fra una demo e un sistema che lavora da sette mesi.</p></section>
<section id="quando-passa-la-chiamata-alla-segretaria-e-perche"><h2>Quando passa la chiamata alla segretaria, e perché</h2>
<p>Circa una chiamata su quattro, <strong>223 su 872</strong>, finisce alla segretaria. Non è una resa: <strong>l’assistente non passa la chiamata a chi la chiede.</strong> Prima domanda il motivo, e se è una cosa che sa gestire prova a gestirla lui. Passa la chiamata solo se la persona insiste.</p>
<div class="tab motivi"><table><thead><tr><th scope="col">Motivo</th><th scope="col">Chiamate</th></tr></thead><tbody><tr><td>Insiste per parlare con una persona, dopo che l’assistente ha provato</td><td class="num"><span class="barra" style="--f:1.000" aria-hidden="true"></span><strong>111</strong></td></tr><tr><td>Pulizia degli impianti: per regola della clinica la prenota solo la segretaria</td><td class="num"><span class="barra" style="--f:0.234" aria-hidden="true"></span>26</td></tr><tr><td>Non vuole che la chiamata venga registrata</td><td class="num"><span class="barra" style="--f:0.225" aria-hidden="true"></span>25</td></tr><tr><td>Urgenza o dolore</td><td class="num"><span class="barra" style="--f:0.189" aria-hidden="true"></span>21</td></tr><tr><td>Motivo non classificabile</td><td class="num"><span class="barra" style="--f:0.360" aria-hidden="true"></span>40</td></tr></tbody></table></div>
<p class="nota"><em>La classificazione è automatica, fatta sui riassunti delle chiamate: va presa come indicativa.</em></p>
<p>Tutto il resto lo fa da solo, <strong>compreso annullare e spostare un appuntamento</strong>, che di solito si pensa debbano passare per forza da una persona.</p>
<p>C’è poi un caso che esiste ma non si riesce a contare: l’assistente propone gli orari, la persona li rifiuta uno dopo l’altro, e dopo qualche tentativo la chiamata passa alla segretaria. Nei riassunti compare troppo di rado per dargli un numero.</p></section>
<section id="cosa-abbiamo-sbagliato-e-sistemato"><h2>Cosa abbiamo sbagliato, e sistemato</h2>
<p>Se raccontassimo solo quello che è andato bene, sarebbe pubblicità.</p>
<ul><li>La parola «valutazione» nel menu degli appuntamenti era troppo generica, e l’assistente prenotava col dentista sbagliato. Ce ne siamo accorti al secondo reclamo.</li><li>Quando qualcuno chiedeva di parlare con una persona, la frase con cui l’assistente lo rassicurava diceva che era un’intelligenza artificiale, e faceva venire proprio il dubbio che voleva togliere. L’abbiamo riscritta in modo neutro.</li><li>L’ultimo aggiornamento è partito al terzo tentativo: i primi due li hanno bocciati i test, prima che arrivassero alle chiamate vere.</li></ul></section>
<section id="quanto-ha-fatto-guadagnare-in-una-stima"><h2>Quanto ha fatto guadagnare, in una stima</h2>
<p>Il fatturato vero lo conosce solo la clinica. Una stima onesta però si può fare: per ogni appuntamento l’assistente ha registrato il trattamento e se il paziente era nuovo, e il listino dice quanto costa ciascuno.</p>
<figure class="stima"><div class="passo"><span class="et">Appuntamenti presi, a prezzo di listino</span><span class="traccia"><span class="pezzo primo" style="--da:0.00%;--l:9.07%"></span></span><span class="val">5.200 €</span></div><div class="passo"><span class="et">Trattamenti chiesti dai pazienti nuovi</span><span class="traccia"><span class="pezzo" style="--da:9.07%;--l:2.40%"></span></span><span class="val">+1.400 €</span></div><div class="passo"><span class="et">Impianti, se metà delle 23 prime visite diventa un trattamento</span><span class="traccia"><span class="pezzo" style="--da:11.47%;--l:44.27%"></span></span><span class="val">+25.400 €</span></div><div class="passo totale"><span class="et">Totale stimato in sette mesi</span><span class="traccia"><span class="pezzo pieno" style="--da:0%;--l:55.74%"></span><span class="pezzo fantasma" style="--da:55.74%;--l:44.26%"></span></span><span class="val">circa 32.000 €</span></div><p class="stima-max">Se tutte le visite per impianti diventassero un trattamento: circa 57.000 €</p></figure>
<p class="nota"><em>Stima su listino. Le visite per impianti valgono la media dei trattamenti del programma della clinica, circa 2.200 € l’una: si va da 745 € per un impianto singolo a 4.800 € per un’arcata completa. Prima visita dei pazienti nuovi a 20 €, e non è tolto chi non si è presentato.</em></p>
<p>Secondo noi il numero che conta di più è un altro: <strong>23 prime visite per impianti in sette mesi</strong>. È la parte più cara del listino, e basta che una diventi un’arcata completa per valere quasi 5.000 euro.</p></section>
<section id="domande-frequenti"><h2>Domande frequenti</h2>
<div class="faq"><details open><summary>Quante chiamate ha gestito l’assistente vocale?</summary><p>Dal 1° febbraio al 9 settembre 2026 ha risposto a 872 chiamate: 527 si sono chiuse senza passare dalla segretaria, 223 sono passate a lei e 122 si sono chiuse nei primi 10 secondi. Gli appuntamenti presi sono 114.</p></details><details><summary>In quali lingue risponde?</summary><p>In portoghese europeo, inglese, italiano, spagnolo, francese e tedesco. La chiamata parte in portoghese, e se chi chiama usa un’altra lingua l’assistente la cambia nella risposta successiva, senza passare la chiamata a nessuno.</p></details><details><summary>Cosa fa se un paziente chiama per un’urgenza?</summary><p>La clinica non ha posti per le urgenze, e l’assistente non ne promette. Riconosce il problema, spiega che il primo posto potrebbe essere domani come fra una settimana e propone il primo posto libero oppure la segretaria, se la clinica è aperta.</p></details><details><summary>Quando passa la chiamata a una persona?</summary><p>Quando chi chiama insiste per parlare con una persona dopo che l’assistente ha provato a gestire la richiesta, per la pulizia degli impianti, quando qualcuno non vuole che la chiamata venga registrata e per le urgenze. È successo con 223 chiamate su 872.</p></details><details><summary>Da dove conviene partire con un assistente vocale?</summary><p>Secondo noi da una linea sola, come abbiamo fatto qui con il numero degli annunci: se qualcosa va storto la spegni in un pomeriggio, e se funziona la allarghi.</p></details></div></section>
<section id="per-chiudere"><h2>Per chiudere</h2>
<p>Se hai una clinica o uno studio, secondo noi la domanda giusta non è se un’intelligenza artificiale può rispondere al telefono. È da quale parte del telefono farla partire.</p>
<p>Se vuoi capire come lavora prima di parlarne, qui trovi <a href="/it/voice-ai">come funziona l’assistente vocale</a>.</p>
<div class="cta"><a class="btn" href="https://api.leadconnectorhq.com/widget/bookings/automis-it" target="_blank" rel="noopener">Prenota una chiamata</a><p>Trenta minuti, e ti diciamo da dove partiremmo noi.</p></div></section>
</article>`;
