/* Generato da build.py del secondo cervello (--sito). Non modificare a mano:
   il testo si cambia in testo-articolo.md, lo stile in stile.css. */
export default `<div class="hero">
  <nav class="briciole" aria-label="Breadcrumb"><ol><li><a href="/">Home</a></li><li><a href="/use-cases">Case studies</a></li><li aria-current="page">Clínica Santa Maria dos Olivais</li></ol></nav>
  <h1>7 months on a dental clinic’s phone line</h1>
  <p class="sub">872 calls, 114 appointments, and 527 calls wrapped up by the assistant without ever reaching the front desk.</p>
  <div class="clinica"><span class="tile"><img src="/assets/images/client-logos/clinica-santa-maria.png" alt="Clínica Santa Maria dos Olivais" width="67" height="48"></span><div><b>Clínica Santa Maria dos Olivais</b><span class="dove">Dental practice · Lisbon</span></div></div>
  <figure class="curva" style="--n:8" role="img" aria-label="Chart of calls received by the assistant each month, from February to September 2026: Feb 81, Mar 45, Apr 50, May 34, Jun 154, Jul 168, Aug 275, Sep 65"><figcaption class="curva-testa"><span>Calls per month</span><span class="tot">872 in total</span></figcaption><div class="barre"><div class="col" style="--h:29.5%;--i:0"><span class="v">81</span><span class="b"></span></div><div class="col" style="--h:16.4%;--i:1"><span class="v">45</span><span class="b"></span></div><div class="col" style="--h:18.2%;--i:2"><span class="v">50</span><span class="b"></span></div><div class="col" style="--h:12.4%;--i:3"><span class="v">34</span><span class="b"></span></div><div class="col dopo svolta" style="--h:56.0%;--i:4"><span class="svolta-et">June · Google Maps</span><span class="v">154</span><span class="b"></span></div><div class="col dopo" style="--h:61.1%;--i:5"><span class="v">168</span><span class="b"></span></div><div class="col dopo" style="--h:100.0%;--i:6"><span class="v">275</span><span class="b"></span></div><div class="col dopo" style="--h:23.6%;--i:7"><span class="v">65</span><span class="b"></span></div></div><div class="mesi" aria-hidden="true"><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span><span>Sep</span></div><div class="anni" aria-hidden="true"><span>2026</span></div><p class="nota">Since June the assistant’s number has been on Google Maps. September through the 9th.</p></figure>
  <aside class="breve"><span class="et">In short</span><p>From February 1 to September 9, 2026, an Automis AI voice receptionist answered 872 calls for Clínica Santa Maria dos Olivais, a dental practice in Lisbon with a single receptionist. 527 were wrapped up without reaching her, and 114 ended with an appointment in the calendar. At first it only answered the number from the ads; since June, when the owner came to trust it, it has answered the number on Google Maps.</p></aside>
</div>
<article class="corpo">
<section id="where-it-started"><h2>Where it started</h2>
<p>Clínica Santa Maria dos Olivais is a dental practice in Lisbon: six dentists, each with their own specialties and their own days, and a single receptionist. For a practice like that, the phone is everything. People who can’t get through often don’t call back. They try the next dentist.</p>
<p>Nobody was counting how many calls went unanswered before. The clinic’s own estimate is around ten a day.</p>
<p>The problem wasn’t the technology. It was trust. The owner didn’t want an AI on the phone with her patients, and who could blame her? If the assistant gets it wrong, she’s the one who looks bad.</p></section>
<section id="we-started-small"><h2>We started small</h2>
<p>We didn’t try to win her over with a pitch deck. At first, the voice assistant <strong>only answered the number from the clinic’s ads</strong>. People calling that number have already seen the ad and know what they want. If anything went wrong, we could switch it off in an afternoon without anyone at the clinic noticing.</p></section>
<section id="then-she-trusted-it"><h2>Then she trusted it</h2>
<p>In May the assistant answered 34 calls a month. By August, 275.</p>
<p>It didn’t get eight times better. In June the owner trusted us enough to <strong>hand it all over to the system</strong>: the assistant’s number went live on Google Maps, the one anyone searching for the clinic finds.</p></section>
<section id="the-numbers"><h2>The numbers</h2>
<p class="nota"><em>Production data, February 1 to September 9, 2026.</em></p>
<figure class="ripartizione"><div class="barra-tot" role="img" aria-label="527 Wrapped up by the assistant, 223 Passed to the front desk, 122 Hung up within 10 seconds"><span class="seg s0" style="--p:60.44%"></span><span class="seg s1" style="--p:25.57%"></span><span class="seg s2" style="--p:13.99%"></span></div><ul><li><span class="pal s0"></span><b>527</b><span>Wrapped up by the assistant</span><span class="perc">60%</span></li><li><span class="pal s1"></span><b>223</b><span>Passed to the front desk</span><span class="perc">26%</span></li><li><span class="pal s2"></span><b>122</b><span>Hung up within 10 seconds</span><span class="perc">14%</span></li></ul></figure>
<div class="tab"><table><tbody><tr><td>Calls received by the assistant</td><td><strong>872</strong></td></tr><tr><td>Wrapped up by the assistant, never reaching the front desk</td><td><strong>527</strong></td></tr><tr><td>Passed to the front desk</td><td><strong>223</strong></td></tr><tr><td>Hung up within 10 seconds</td><td><strong>122</strong></td></tr><tr><td>Appointments booked</td><td><strong>114</strong></td></tr><tr><td>Came in after hours or while another call was in progress</td><td><strong>193</strong> (22%)</td></tr><tr><td>Different people it spoke with</td><td><strong>385</strong></td></tr><tr><td>Average conversation length</td><td><strong>1 minute 37 seconds</strong></td></tr><tr><td>Hours of phone time handled</td><td><strong>20.2</strong></td></tr></tbody></table></div></section>
<section id="six-languages-and-it-switches-on-its-own"><h2>Six languages, and it switches on its own</h2>
<p>Lisbon is a multicultural capital, and Portuguese alone doesn’t cover everyone who calls. The assistant answers in <strong>European Portuguese, English, Italian, Spanish, French and German</strong>.</p>
<p>How it does it matters more than the list. Every call starts in Portuguese. If the caller switches language, or asks for another one, the assistant <strong>switches too, in its very next reply</strong>. It doesn’t announce it, doesn’t ask permission, and doesn’t transfer the call.</p></section>
<section id="just-finding-a-free-slot-was-a-job-in-itself"><h2>Just finding a free slot was a job in itself</h2>
<p>Six dentists, none of them full-time. They work split half-days and each one does different things: orthodontics <strong>only on Wednesdays</strong>, pediatric dentistry <strong>only on Tuesdays</strong>, root canals on Tuesdays, Thursdays and Fridays, and implants follow the clinical director’s schedule.</p>
<figure class="settimana"><table><thead><tr><th scope="col"><span class="sr-only">Treatment</span></th><th scope="col">Mon</th><th scope="col">Tue</th><th scope="col">Wed</th><th scope="col">Thu</th><th scope="col">Fri</th></tr></thead><tbody><tr><th scope="row">Orthodontics</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td></tr><tr><th scope="row">Pediatric dentistry</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td></tr><tr><th scope="row">Root canals</th><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto on" role="img" aria-label="yes"></span></td></tr><tr><th scope="row">Implants</th><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto" aria-hidden="true"></span><span class="sr-only">no</span></td><td><span class="punto on" role="img" aria-label="yes"></span></td><td><span class="punto on" role="img" aria-label="yes"></span></td></tr></tbody></table><figcaption>Who’s in, and when, Monday to Friday. Everyone works half-days.</figcaption></figure>
<p>That means some treatments <strong>exist on a single day of the week</strong>. Finding the first free slot isn’t a matter of checking the calendar. Four things have to line up: the treatment, a dentist who does it, a day that dentist is in, and a slot still open that day.</p>
<p><strong>Before any of that, the assistant has to work out what the caller needs.</strong> Nobody on the phone says “endodontics”. They say it hurts, a crown fell off, they want braces or a cleaning. There are twenty-one treatment types to recognize from everyday speech, because that word decides which dentist the patient sees. That’s exactly where the system slipped once: the word “assessment” covered too much and sent patients to the wrong dentist.</p></section>
<section id="how-it-looks-for-a-slot"><h2>How it looks for a slot</h2>
<ul><li>It always offers <strong>exactly two times</strong>. Never one, never a list.</li><li>If neither works, it looks for two more <strong>further ahead</strong>, and never offers a rejected time again.</li><li>If the calendar returns the same times, earlier times or nothing, it treats that as a <strong>logical failure</strong> and stops after two attempts.</li><li>Then it stops pushing. During opening hours it passes the call to the front desk; after hours it offers a callback.</li></ul>
<p>A system that keeps querying a full calendar until something turns up is the easiest thing to build, and the worst thing to put on a phone line.</p></section>
<section id="emergencies-where-it-has-to-say-something-uncomfortable"><h2>Emergencies, where it has to say something uncomfortable</h2>
<p>The clinic works by appointment only and <strong>has no emergency slots</strong>. When the assistant picks up on severe pain, a broken tooth, swelling or bleeding, it doesn’t promise anything. It acknowledges the problem in one sentence, explains that the first slot could be tomorrow or a week away, and offers two options: the first available slot, or the front desk if the clinic is open.</p>
<p>Promising a same-day slot to someone in pain is easy to program and impossible to keep. That’s the difference between a demo and a system that has been live for seven months.</p></section>
<section id="when-it-hands-the-call-to-a-person-and-why"><h2>When it hands the call to a person, and why</h2>
<p>About one call in four, <strong>223 out of 872</strong>, ends up with the receptionist. That isn’t the assistant giving up: <strong>it doesn’t transfer people just because they ask.</strong> It asks why they’re calling first, and if it’s something it can handle, it tries to handle it. It only transfers if the caller insists.</p>
<div class="tab motivi"><table><thead><tr><th scope="col">Reason</th><th scope="col">Calls</th></tr></thead><tbody><tr><td>Insists on a person, after the assistant tried to help</td><td class="num"><span class="barra" style="--f:1.000" aria-hidden="true"></span><strong>111</strong></td></tr><tr><td>Implant cleaning: clinic policy says only the front desk books it</td><td class="num"><span class="barra" style="--f:0.234" aria-hidden="true"></span>26</td></tr><tr><td>Doesn’t want the call recorded</td><td class="num"><span class="barra" style="--f:0.225" aria-hidden="true"></span>25</td></tr><tr><td>Emergency or pain</td><td class="num"><span class="barra" style="--f:0.189" aria-hidden="true"></span>21</td></tr><tr><td>Couldn’t be classified</td><td class="num"><span class="barra" style="--f:0.360" aria-hidden="true"></span>40</td></tr></tbody></table></div>
<p class="nota"><em>Classified automatically from call summaries, so treat these as indicative.</em></p>
<p>Everything else it handles on its own, <strong>including cancelling and rescheduling appointments</strong>, the two things most people assume need a human.</p>
<p>There’s one more case that exists but can’t be counted: the assistant offers times, the caller turns them down one after another, and after a few tries the call goes to the front desk. It shows up too rarely in the summaries to put a number on it.</p></section>
<section id="what-we-got-wrong-and-fixed"><h2>What we got wrong, and fixed</h2>
<p>If we only told you what went well, it would be an ad.</p>
<ul><li>The word “assessment” in the appointment menu was too vague, and the assistant booked patients with the wrong dentist. We caught it on the second complaint.</li><li>When someone asked to speak to a person, the line the assistant used to reassure them mentioned that it was an AI, and planted exactly the doubt it was meant to remove. We rewrote it to be neutral.</li><li>The latest update went live on the third attempt. Our tests rejected the first two before they ever reached a real call.</li></ul></section>
<section id="what-it-brought-in-as-an-estimate"><h2>What it brought in, as an estimate</h2>
<p>Only the clinic knows the real revenue, but an honest estimate is possible: for every appointment the assistant logged the treatment and whether the patient was new, and the price list says what each one costs.</p>
<figure class="stima"><div class="passo"><span class="et">Appointments booked, at list price</span><span class="traccia"><span class="pezzo primo" style="--da:0.00%;--l:9.07%"></span></span><span class="val">€5,200</span></div><div class="passo"><span class="et">Treatments requested by new patients</span><span class="traccia"><span class="pezzo" style="--da:9.07%;--l:2.40%"></span></span><span class="val">+€1,400</span></div><div class="passo"><span class="et">Implants, if half of the 23 consultations become treatment</span><span class="traccia"><span class="pezzo" style="--da:11.47%;--l:44.27%"></span></span><span class="val">+€25,400</span></div><div class="passo totale"><span class="et">Estimated total in seven months</span><span class="traccia"><span class="pezzo pieno" style="--da:0%;--l:55.74%"></span><span class="pezzo fantasma" style="--da:55.74%;--l:44.26%"></span></span><span class="val">about €32,000</span></div><p class="stima-max">If every implant consultation became treatment: about €57,000</p></figure>
<p class="nota"><em>Estimate at list prices. Implant consultations are valued at the average of the clinic’s implant programme, about €2,200 each: from €745 for a single implant to €4,800 for a full arch. New patients’ first visit at €20, and no-shows are not subtracted.</em></p>
<p>In our view the number that matters most is a different one: <strong>23 first visits for implants in seven months</strong>. It’s the most expensive part of the price list, and one of them turning into a full arch is worth almost €5,000.</p></section>
<section id="frequently-asked-questions"><h2>Frequently asked questions</h2>
<div class="faq"><details open><summary>How many calls did the AI voice receptionist handle?</summary><p>From February 1 to September 9, 2026 it answered 872 calls: 527 were wrapped up without reaching the front desk, 223 were passed to the receptionist and 122 were hung up within the first 10 seconds. It booked 114 appointments.</p></details><details><summary>Which languages does it speak?</summary><p>European Portuguese, English, Italian, Spanish, French and German. Every call starts in Portuguese, and if the caller uses another language the assistant switches in its next reply, without transferring the call.</p></details><details><summary>What happens when a patient calls with an emergency?</summary><p>The clinic has no emergency slots, and the assistant doesn’t promise any. It acknowledges the problem, explains that the first slot could be tomorrow or a week away, and offers the first available slot or the front desk if the clinic is open.</p></details><details><summary>When does it hand the call to a person?</summary><p>When the caller insists on a person after the assistant has tried to help, for implant cleanings, when someone doesn’t want the call recorded, and for emergencies. That happened on 223 calls out of 872.</p></details><details><summary>Where should you start with an AI voice receptionist?</summary><p>In our view, with a single line, the way we did here with the ads number: if something goes wrong you switch it off in an afternoon, and if it works you expand it.</p></details></div></section>
<section id="the-close"><h2>The close</h2>
<p>If you run a clinic or a practice, the question isn’t whether AI can answer your phone. It’s which part of your phone to start it on.</p>
<p>If you’d like to see how it works before we talk, here’s <a href="/voice-ai">how the AI voice receptionist works</a>.</p>
<div class="cta"><a class="btn" href="https://api.leadconnectorhq.com/widget/bookings/discover-automis" target="_blank" rel="noopener">Book a call</a><p>Thirty minutes, and we’ll tell you where we’d start.</p></div></section>
</article>`;
